import Foundation

// MARK: - 题库（按高考权重配题）
// 规则：weight=3 高频考点 每点 ≥2 题（选择+简答采分混配）；weight=2 配 1–2；weight=1 暂不配。
// 红线：题干、答案、采分点、解析均经核对，不臆造试题出处。
// 当前先为已深化的高频考点配题，其余随内容建设增量补齐。

enum QuestionData {
    static let all: [Question] = [
        photosynthesis, respiration, meiosis, mendel, expression, glucose,
        protein, nucleicAcid, membrane, organelle, transport, enzyme, atp, anaerobic,
        mitosis, secretory, photoFactors, sexLinked, dnaStructure, variation, evolution,
        internalEnv, nerve, immune, population, energyFlow, carbonCycle, stability, geneEng,
        cellJunior, circulation,
        nerveSynapse, materialCycle, geneticsMore, homeostasisMore, ecologyMore, biotechMore,
        geneticsFill, homeostasisFill, ecologyFill, biotechFill,
        geneticsDense, homeostasisDense, ecologyDense, biotechDense,
        geneticsDense2, homeostasisDense2, homeostasisDense3, ecologyDense2, biotechDense2,
    ].flatMap { $0 }

    static func questions(for kpId: String) -> [Question] { all.filter { $0.kpId == kpId } }
    static func hasQuestions(_ kpId: String) -> Bool { all.contains { $0.kpId == kpId } }

    // 光反应
    private static let photosynthesis: [Question] = [
        Question(id: "q_photo1_c1", kpId: "m1_photo_01", type: .choice,
                 stem: "光合作用光反应阶段，下列说法正确的是？",
                 explanation: "水的光解发生在类囊体薄膜，产生 [H] 和 O₂，并将光能转化为 ATP 中的化学能；O₂ 全部来自水。",
                 options: ["水在类囊体薄膜上被光解，产生 [H] 和 O₂", "暗反应为光反应提供 [H]", "光反应在叶绿体基质中进行", "O₂ 来自 CO₂"],
                 answerIndex: 0),
        Question(id: "q_photo1_s1", kpId: "m1_photo_01", type: .shortAnswer,
                 stem: "突然停止光照，短时间内叶绿体中 C₃ 和 C₅ 含量将如何变化？为什么？",
                 explanation: "停光后光反应停止供应 [H] 和 ATP。",
                 modelAnswer: "C₃ 含量增多，C₅ 含量减少。因为停光后光反应不再提供 [H] 和 ATP，C₃ 还原受阻而积累，同时 CO₂ 仍在被 C₅ 固定生成 C₃，使 C₅ 减少。",
                 scorePoints: ["C₃ 增多、C₅ 减少", "光反应停止、[H] 和 ATP 减少", "C₃ 还原受阻", "CO₂ 固定仍消耗 C₅"]),
        Question(id: "q_photo2_c1", kpId: "m1_photo_02", type: .choice,
                 stem: "暗反应（卡尔文循环）进行的场所和必需条件是？",
                 explanation: "暗反应在叶绿体基质，不直接需光，但需要光反应提供的 [H] 和 ATP 及多种酶。",
                 options: ["叶绿体基质；需光反应供 [H] 和 ATP", "类囊体薄膜；需光", "线粒体基质；需 O₂", "细胞质基质；需 ATP"],
                 answerIndex: 0),
        Question(id: "q_photo2_c2", kpId: "m1_photo_02", type: .choice,
                 stem: "下列属于暗反应中「CO₂ 固定」的反应是？",
                 explanation: "CO₂ 固定：CO₂ + C₅ → 2C₃；C₃ 还原才需要 [H] 和 ATP。",
                 options: ["CO₂ + C₅ → 2C₃", "C₃ + [H] + ATP → (CH₂O) + C₅", "H₂O → [H] + O₂", "ADP + Pi → ATP"],
                 answerIndex: 0),
    ]

    // 有氧呼吸
    private static let respiration: [Question] = [
        Question(id: "q_resp1_c1", kpId: "m1_resp_01", type: .choice,
                 stem: "有氧呼吸过程中，CO₂ 和 H₂O 的生成阶段分别是？",
                 explanation: "CO₂ 在第二阶段（线粒体基质，丙酮酸分解）生成；H₂O 在第三阶段（线粒体内膜，[H]+O₂）生成。",
                 options: ["CO₂ 第二阶段、H₂O 第三阶段", "都在第一阶段", "CO₂ 第三阶段、H₂O 第二阶段", "都在线粒体内膜"],
                 answerIndex: 0),
        Question(id: "q_resp1_s1", kpId: "m1_resp_01", type: .shortAnswer,
                 stem: "为什么有氧呼吸释放的能量远多于无氧呼吸？",
                 explanation: "有氧呼吸把有机物彻底氧化分解。",
                 modelAnswer: "有氧呼吸中有机物被彻底氧化分解为 CO₂ 和 H₂O，[H] 经第三阶段与 O₂ 结合释放大量能量；无氧呼吸只把葡萄糖分解为酒精或乳酸，分解不彻底，释放能量少。",
                 scorePoints: ["有氧呼吸彻底氧化分解为 CO₂ 和 H₂O", "[H] 与 O₂ 结合释放大量能量", "无氧呼吸分解不彻底（生成酒精/乳酸）"]),
    ]

    // 减数分裂
    private static let meiosis: [Question] = [
        Question(id: "q_meio_c1", kpId: "g_meiosis_01", type: .choice,
                 stem: "同源染色体的分开发生在减数分裂的？",
                 explanation: "同源染色体在减Ⅰ后期分开（使染色体数目减半）；姐妹染色单体在减Ⅱ后期分开。",
                 options: ["减Ⅰ后期", "减Ⅱ后期", "减Ⅰ前期", "减Ⅱ中期"],
                 answerIndex: 0),
        Question(id: "q_meio_c2", kpId: "g_meiosis_01", type: .choice,
                 stem: "一个基因型为 AaBb（两对基因独立）的精原细胞，减数分裂可产生几种精子？",
                 explanation: "一个精原细胞减数分裂只产生 2 种（4 个）精子；一个个体（许多细胞）才可能产生 4 种。",
                 options: ["2 种", "4 种", "1 种", "8 种"],
                 answerIndex: 0),
    ]

    // 分离 / 自由组合
    private static let mendel: [Question] = [
        Question(id: "q_mendel1_c1", kpId: "g_mendel_01", type: .choice,
                 stem: "基因型 Aa 的个体自交，后代表现型及比例（完全显性）为？",
                 explanation: "Aa×Aa → 1AA:2Aa:1aa，表现型显:隐 = 3:1。",
                 options: ["显性:隐性 = 3:1", "全为显性", "1:1", "1:2:1"],
                 answerIndex: 0),
        Question(id: "q_mendel1_c2", kpId: "g_mendel_01", type: .choice,
                 stem: "测交（Aa × aa）后代的表现型比例是？该方法常用来？",
                 explanation: "测交后代 1Aa:1aa，即显:隐 = 1:1，常用来测定显性个体的基因型。",
                 options: ["1:1；测定 F₁ 的基因型", "3:1；测定显隐性", "1:2:1；判断纯合子", "全显性；鉴定纯合"],
                 answerIndex: 0),
        Question(id: "q_mendel2_c1", kpId: "g_mendel_02", type: .choice,
                 stem: "AaBb×AaBb（两对独立），后代中 aabb 的比例是？",
                 explanation: "拆分相乘：aa 占 1/4，bb 占 1/4，相乘 = 1/16。",
                 options: ["1/16", "9/16", "1/4", "3/16"],
                 answerIndex: 0),
        Question(id: "q_mendel2_s1", kpId: "g_mendel_02", type: .shortAnswer,
                 stem: "AaBb×AaBb（两对独立遗传），求后代表现型为「双显性」(A_B_) 的概率，并说明用了什么方法。",
                 explanation: "自由组合题拆成分离定律相乘。",
                 modelAnswer: "A_ 占 3/4、B_ 占 3/4，相乘得 A_B_ = 9/16。方法：把自由组合拆成两个分离定律，分别求概率再相乘。",
                 scorePoints: ["A_ = 3/4、B_ = 3/4", "相乘 = 9/16", "拆成分离定律再相乘（乘法原理）"]),
    ]

    // 基因表达
    private static let expression: [Question] = [
        Question(id: "q_expr_c1", kpId: "g_expr_01", type: .choice,
                 stem: "决定一个氨基酸的密码子位于？",
                 explanation: "密码子在 mRNA 上，每 3 个相邻碱基为一个密码子；tRNA 上是反密码子。",
                 options: ["mRNA 上", "tRNA 上", "DNA 模板链上", "核糖体上"],
                 answerIndex: 0),
        Question(id: "q_expr_s1", kpId: "g_expr_01", type: .shortAnswer,
                 stem: "一个含 900 个碱基的基因（编码区连续），最多可指导合成含多少个氨基酸的蛋白质？写出推算。",
                 explanation: "基因(DNA)碱基:mRNA碱基:氨基酸 = 6:3:1。",
                 modelAnswer: "约 150 个。基因双链 900 个碱基，对应 mRNA 450 个碱基（一条链转录），每 3 个碱基决定 1 个氨基酸，900÷6=150（不计终止密码子）。",
                 scorePoints: ["碱基∶氨基酸 = 6∶1", "900÷6 = 150", "（终止密码子不编码氨基酸，实际略少）"]),
    ]

    // 血糖调节
    private static let glucose: [Question] = [
        Question(id: "q_glu_c1", kpId: "h_humor_01", type: .choice,
                 stem: "下列关于血糖调节的叙述，正确的是？",
                 explanation: "胰岛素是唯一降血糖的激素，由胰岛 B 细胞分泌；胰高血糖素升血糖，两者拮抗。",
                 options: ["胰岛素是唯一能降低血糖的激素", "胰高血糖素由胰岛 B 细胞分泌", "胰岛素促进肝糖原分解", "二者作用相同"],
                 answerIndex: 0),
        Question(id: "q_glu_s1", kpId: "h_humor_01", type: .shortAnswer,
                 stem: "饭后血糖升高时，机体如何把血糖降回正常？（写出主要激素与作用）",
                 explanation: "血糖升高→胰岛B细胞→胰岛素。",
                 modelAnswer: "血糖升高刺激胰岛 B 细胞分泌胰岛素增多；胰岛素促进组织细胞摄取、利用和储存葡萄糖（合成肝糖原、肌糖原），并抑制肝糖原分解和非糖物质转化为葡萄糖，从而使血糖降回正常。这属于（负）反馈调节。",
                 scorePoints: ["胰岛 B 细胞分泌胰岛素增多", "促进摄取、利用、储存（合成糖原）", "抑制糖原分解和非糖物质转化", "负反馈调节"]),
    ]

    // 蛋白质
    private static let protein: [Question] = [
        Question(id: "q_prot_c1", kpId: "m1_mol_03", type: .choice,
                 stem: "一条由 100 个氨基酸构成的肽链，脱水缩合时形成的肽键数和脱去的水分子数分别是？",
                 explanation: "一条肽链中，肽键数=脱去水分子数=氨基酸数−肽链数=100−1=99。",
                 options: ["99 个、99 个", "100 个、100 个", "99 个、100 个", "100 个、99 个"],
                 answerIndex: 0),
        Question(id: "q_prot_s1", kpId: "m1_mol_03", type: .shortAnswer,
                 stem: "蛋白质分子结构和功能多种多样，其根本原因是什么？",
                 explanation: "从氨基酸的四个变量与空间结构作答。",
                 modelAnswer: "蛋白质的多样性源于组成它的氨基酸的种类不同、数目成百上千、排列顺序千变万化，以及肽链盘曲折叠形成的空间结构各异，因而形成结构和功能千差万别的蛋白质。",
                 scorePoints: ["氨基酸种类不同", "数目不同", "排列顺序不同", "肽链的空间结构不同"]),
    ]

    // 核酸
    private static let nucleicAcid: [Question] = [
        Question(id: "q_na_c1", kpId: "m1_mol_04", type: .choice,
                 stem: "下列关于 DNA 和 RNA 的叙述，正确的是？",
                 explanation: "DNA 含脱氧核糖、碱基 A/T/G/C；RNA 含核糖、碱基 A/U/G/C。两者都含磷酸。",
                 options: ["DNA 含脱氧核糖，RNA 含核糖", "DNA 含碱基 U，RNA 含碱基 T", "二者都是双链结构", "二者的基本单位都是氨基酸"],
                 answerIndex: 0),
        Question(id: "q_na_c2", kpId: "m1_mol_04", type: .choice,
                 stem: "组成核酸的基本单位是？",
                 explanation: "核酸的基本单位是核苷酸，由一分子磷酸、一分子五碳糖和一分子含氮碱基构成。",
                 options: ["核苷酸", "氨基酸", "葡萄糖", "甘油"],
                 answerIndex: 0),
    ]

    // 细胞膜
    private static let membrane: [Question] = [
        Question(id: "q_mem_c1", kpId: "m1_cell_01", type: .choice,
                 stem: "细胞膜的基本支架是？",
                 explanation: "流动镶嵌模型中，磷脂双分子层构成基本支架，蛋白质镶嵌、贯穿或覆盖其上。",
                 options: ["磷脂双分子层", "蛋白质", "纤维素", "糖蛋白"],
                 answerIndex: 0),
        Question(id: "q_mem_s1", kpId: "m1_cell_01", type: .shortAnswer,
                 stem: "细胞膜能控制物质进出，但这种控制是“相对”的，请说明原因。",
                 explanation: "从选择透过性与不能完全阻挡两方面作答。",
                 modelAnswer: "细胞膜具有选择透过性，可让需要的营养物质进入、代谢废物和分泌物排出，对物质进出有选择作用；但这种控制是相对的，环境中一些有害物质（如病毒、某些有毒物质）有时也能进入细胞。",
                 scorePoints: ["细胞膜具有选择透过性", "保证营养物质进入、废物排出", "控制是相对的，有害物质有时也能进入"]),
    ]

    // 细胞器分工
    private static let organelle: [Question] = [
        Question(id: "q_org_c1", kpId: "m1_cell_02", type: .choice,
                 stem: "下列细胞器与其主要功能对应正确的是？",
                 explanation: "核糖体是蛋白质合成场所；线粒体是有氧呼吸主要场所；叶绿体是光合场所；高尔基体加工分类分泌物。",
                 options: ["核糖体——合成蛋白质", "线粒体——光合作用", "叶绿体——有氧呼吸主要场所", "核糖体——加工分泌蛋白"],
                 answerIndex: 0),
        Question(id: "q_org_c2", kpId: "m1_cell_02", type: .choice,
                 stem: "既存在于植物细胞、又存在于动物细胞，且与能量转换有关的细胞器是？",
                 explanation: "线粒体是动植物细胞共有的“动力车间”；叶绿体只存在于绿色植物等自养细胞。",
                 options: ["线粒体", "叶绿体", "液泡", "中心体"],
                 answerIndex: 0),
    ]

    // 物质运输（被动 + 主动）
    private static let transport: [Question] = [
        Question(id: "q_trans_c1", kpId: "m1_trans_01", type: .choice,
                 stem: "O₂、CO₂、水分子进出细胞的方式是？",
                 explanation: "O₂、CO₂、水等小分子顺浓度梯度、不需载体、不耗能，属于自由扩散。",
                 options: ["自由扩散", "协助扩散", "主动运输", "胞吞胞吐"],
                 answerIndex: 0),
        Question(id: "q_trans_c2", kpId: "m1_trans_02", type: .choice,
                 stem: "既需要载体蛋白、又需要消耗 ATP 的物质运输方式是？",
                 explanation: "主动运输逆浓度梯度运输，同时需要载体蛋白和能量；协助扩散需载体但不耗能。",
                 options: ["主动运输", "自由扩散", "协助扩散", "渗透作用"],
                 answerIndex: 0),
        Question(id: "q_trans_s1", kpId: "m1_trans_02", type: .shortAnswer,
                 stem: "细胞主动运输对生命活动有何意义？",
                 explanation: "从“逆浓度梯度”“按需选择”角度作答。",
                 modelAnswer: "主动运输能逆浓度梯度运输物质，保证活细胞按照生命活动的需要，主动地选择吸收所需要的营养物质、排出代谢废物和对细胞有害的物质，从而维持细胞正常的代谢和内部环境的稳定。",
                 scorePoints: ["逆浓度梯度运输", "按需主动选择吸收营养物质", "排出废物和有害物质", "维持细胞正常代谢/稳态"]),
        Question(id: "q_trans_c3", kpId: "m1_trans_01", type: .choice,
                 stem: "葡萄糖进入人成熟红细胞的运输方式是？",
                 explanation: "葡萄糖进入红细胞顺浓度梯度、需要载体蛋白但不消耗 ATP，属于协助扩散。",
                 options: ["协助扩散（顺浓度、需载体、不耗能）", "自由扩散", "主动运输", "胞吞"],
                 answerIndex: 0),
    ]

    // 酶
    private static let enzyme: [Question] = [
        Question(id: "q_enz_c1", kpId: "m1_enzyme_01", type: .choice,
                 stem: "关于酶的叙述，正确的是？",
                 explanation: "酶通过降低化学反应的活化能起催化作用，反应前后本身的性质和数量不变，不改变反应的平衡点。",
                 options: ["酶通过降低活化能起催化作用", "酶能为反应提供能量", "酶在反应后被消耗", "酶能改变反应的平衡点"],
                 answerIndex: 0),
        Question(id: "q_enz_c2", kpId: "m1_enzyme_03", type: .choice,
                 stem: "关于温度对酶活性影响的叙述，正确的是？",
                 explanation: "低温只抑制酶活性、酶不变性，升温后可恢复；高温使酶变性、永久失活。",
                 options: ["低温下酶活性低但不失活，升温后可恢复", "低温使酶永久失活", "高温下酶活性最高", "高温使酶失活后降温可恢复"],
                 answerIndex: 0),
        Question(id: "q_enz_c3", kpId: "m1_enzyme_03", type: .choice,
                 stem: "关于 pH 对酶活性的影响，正确的是？",
                 explanation: "每种酶都有最适 pH，偏离最适（过酸或过碱）都会使酶变性失活，且不能因恢复中性而复活。",
                 options: ["过酸或过碱都会使酶变性失活，且不可恢复", "pH 越高酶活性越高", "过酸只抑制活性，恢复中性后酶可复活", "pH 不影响酶活性"],
                 answerIndex: 0),
        Question(id: "q_enz_s1", kpId: "m1_enzyme_01", type: .shortAnswer,
                 stem: "与无机催化剂相比，酶的催化作用有哪些特性？",
                 explanation: "答高效性、专一性、作用条件温和。",
                 modelAnswer: "酶的催化具有高效性（催化效率远高于无机催化剂）、专一性（每种酶只能催化一种或一类化学反应）和作用条件较温和（在常温常压、适宜 pH 下催化，过酸、过碱或高温都会使酶变性失活）。",
                 scorePoints: ["高效性", "专一性", "作用条件温和（适宜温度、pH）"]),
    ]

    // ATP
    private static let atp: [Question] = [
        Question(id: "q_atp_c1", kpId: "m1_enzyme_02", type: .choice,
                 stem: "关于 ATP 的叙述，正确的是？",
                 explanation: "ATP 结构简式 A—P~P~P，含两个高能磷酸键；远离 A 的高能磷酸键水解释放能量，ATP 与 ADP 可相互转化。",
                 options: ["ATP 是细胞的直接能源物质", "ATP 中含 3 个高能磷酸键", "ATP 水解时形成高能磷酸键", "ADP 不能转化为 ATP"],
                 answerIndex: 0),
        Question(id: "q_atp_c2", kpId: "m1_enzyme_02", type: .choice,
                 stem: "活细胞中 ATP 与 ADP 的相互转化中，合成 ATP 所需能量主要来自？",
                 explanation: "动物和人体合成 ATP 的能量来自呼吸作用；绿色植物还可来自光合作用（光反应）。",
                 options: ["呼吸作用（绿色植物还有光合作用）", "只来自光合作用", "蒸腾作用", "细胞分裂"],
                 answerIndex: 0),
    ]

    // 无氧呼吸
    private static let anaerobic: [Question] = [
        Question(id: "q_anae_c1", kpId: "m1_resp_02", type: .choice,
                 stem: "关于无氧呼吸的叙述，正确的是？",
                 explanation: "无氧呼吸全过程在细胞质基质进行，不消耗 O₂、不在线粒体；产物为乳酸或酒精加 CO₂。",
                 options: ["全过程在细胞质基质中进行", "在线粒体中进行", "需要消耗 O₂", "产物一定是乳酸"],
                 answerIndex: 0),
        Question(id: "q_anae_s1", kpId: "m1_resp_02", type: .shortAnswer,
                 stem: "马铃薯块茎和人体骨骼肌细胞在无氧条件下的呼吸产物分别是什么？",
                 explanation: "植物（除少数）和动物无氧呼吸产物不同。",
                 modelAnswer: "马铃薯块茎（及高等植物、乳酸菌）无氧呼吸的产物是乳酸；人体骨骼肌细胞剧烈运动缺氧时无氧呼吸的产物也是乳酸。而酵母菌等无氧呼吸产物是酒精和 CO₂。",
                 scorePoints: ["马铃薯块茎产物为乳酸", "骨骼肌细胞产物为乳酸", "（对比）酵母菌产酒精和 CO₂"]),
    ]

    // 有丝分裂
    private static let mitosis: [Question] = [
        Question(id: "q_mit_c1", kpId: "m1_prolif_01", type: .choice,
                 stem: "有丝分裂中，姐妹染色单体分开、染色体数目暂时加倍发生在？",
                 explanation: "后期着丝点（粒）分裂，姐妹染色单体分开移向两极，细胞内染色体数目暂时加倍。",
                 options: ["后期", "间期", "前期", "中期"],
                 answerIndex: 0),
        Question(id: "q_mit_c2", kpId: "m1_prolif_01", type: .choice,
                 stem: "观察染色体形态、数目的最佳时期是有丝分裂的？",
                 explanation: "中期染色体形态稳定、数目清晰，是观察和计数染色体的最佳时期。",
                 options: ["中期", "间期", "前期", "末期"],
                 answerIndex: 0),
    ]

    // 分泌蛋白的合成与运输
    private static let secretory: [Question] = [
        Question(id: "q_sec_c1", kpId: "m1_cell_04", type: .choice,
                 stem: "分泌蛋白（如消化酶、抗体）合成、加工和分泌的正确途径是？",
                 explanation: "核糖体合成肽链→内质网加工折叠→高尔基体进一步加工分类→以分泌小泡形式经细胞膜排出，全程线粒体供能。",
                 options: ["核糖体→内质网→高尔基体→细胞膜", "高尔基体→内质网→核糖体→细胞膜", "内质网→核糖体→高尔基体→细胞膜", "核糖体→高尔基体→内质网→细胞膜"],
                 answerIndex: 0),
        Question(id: "q_sec_s1", kpId: "m1_cell_04", type: .shortAnswer,
                 stem: "分泌蛋白的合成和运输过程中，线粒体起什么作用？膜结构之间通过什么方式联系？",
                 explanation: "考查能量供应与囊泡运输。",
                 modelAnswer: "线粒体通过有氧呼吸为分泌蛋白的合成、加工和运输（分泌）过程提供能量（ATP）；内质网、高尔基体和细胞膜等之间通过具膜的小泡（囊泡）的转移而相互联系、相互转化，体现生物膜系统在结构和功能上的联系。",
                 scorePoints: ["线粒体供能（ATP）", "通过囊泡（小泡）运输联系", "体现生物膜系统的统一/转化"]),
    ]

    // 影响光合作用的因素 / 总净光合
    private static let photoFactors: [Question] = [
        Question(id: "q_pf_c1", kpId: "m1_photo_04", type: .choice,
                 stem: "在一定范围内，要提高大棚蔬菜的光合作用速率，下列措施无效的是？",
                 explanation: "适当增大光照强度、提高 CO₂ 浓度、保持适宜温度都能提高光合速率；降低昼夜温差不利于有机物积累。",
                 options: ["夜间适当降低温度以减少呼吸消耗——错误，这正是有效措施", "适当增施 CO₂", "保持适宜温度", "适当增强光照"],
                 answerIndex: 0),
        Question(id: "q_pf_s1", kpId: "m1_photo_05", type: .shortAnswer,
                 stem: "测得某植物叶片在光下每小时释放 O₂ 6 mg，在黑暗中每小时吸收 O₂ 2 mg。求该叶片每小时真正（总）光合作用产生的 O₂ 量，并写出关系式。",
                 explanation: "总光合 = 净光合 + 呼吸消耗。",
                 modelAnswer: "总（真正）光合速率 = 表观（净）光合速率 + 呼吸速率。光下释放 O₂ 6 mg 为净光合量，黑暗吸收 O₂ 2 mg 为呼吸量，所以总光合产生 O₂ = 6 + 2 = 8 mg。",
                 scorePoints: ["总光合 = 净光合 + 呼吸", "净光合 = 6 mg、呼吸 = 2 mg", "总光合 = 8 mg"]),
        Question(id: "q_pf_c2", kpId: "m1_photo_04", type: .choice,
                 stem: "在一定范围内增强光照，光合速率加快，主要是因为光照直接影响了？",
                 explanation: "光照强度直接影响光反应，光越强产生的 [H] 和 ATP 越多，进而促进暗反应。",
                 options: ["光反应（产生更多 [H] 和 ATP）", "暗反应中 CO₂ 的固定", "呼吸作用", "蒸腾作用"],
                 answerIndex: 0),
        Question(id: "q_pf_c3", kpId: "m1_photo_05", type: .choice,
                 stem: "关于总光合速率与净光合速率，正确的是？",
                 explanation: "总（真正）光合速率 = 净（表观）光合速率 + 呼吸速率；黑暗中无光合，只能测呼吸。",
                 options: ["总（真正）光合 = 净（表观）光合 + 呼吸速率", "净光合 = 总光合 + 呼吸", "黑暗中能直接测出总光合", "净光合一定大于总光合"],
                 answerIndex: 0),
    ]

    // 伴性遗传
    private static let sexLinked: [Question] = [
        Question(id: "q_sex_c1", kpId: "g_sex_01", type: .choice,
                 stem: "人类红绿色盲（伴 X 隐性遗传）的遗传特点是？",
                 explanation: "伴 X 隐性遗传男性只需一个致病基因即患病，故男患者多于女患者，且常表现交叉遗传（外祖父→母亲→外孙）。",
                 options: ["男性患者多于女性患者", "女性患者多于男性患者", "只在女性中出现", "与性别无关"],
                 answerIndex: 0),
        Question(id: "q_sex_s1", kpId: "g_sex_01", type: .shortAnswer,
                 stem: "一对表现型正常的夫妇生了一个红绿色盲的儿子，写出双亲的基因型，并解释儿子的色盲基因来自谁。（用 Xᴮ、Xᵇ 表示）",
                 explanation: "色盲为伴 X 隐性，儿子的 X 来自母亲。",
                 modelAnswer: "父亲表现正常，基因型为 XᴮY；母亲表现正常但生出色盲儿子（XᵇY），说明母亲是携带者，基因型为 XᴮXᵇ。儿子的 Y 来自父亲、X 来自母亲，色盲基因 Xᵇ 来自母亲。",
                 scorePoints: ["父亲 XᴮY", "母亲 XᴮXᵇ（携带者）", "儿子色盲基因来自母亲"]),
    ]

    // DNA 结构、复制与碱基计算
    private static let dnaStructure: [Question] = [
        Question(id: "q_dna_c1", kpId: "g_dna_02", type: .choice,
                 stem: "DNA 分子复制的方式和特点是？",
                 explanation: "DNA 复制为半保留复制，边解旋边复制；以两条母链为模板，遵循碱基互补配对。",
                 options: ["半保留复制，边解旋边复制", "全保留复制", "只以一条链为模板", "不需要解旋"],
                 answerIndex: 0),
        Question(id: "q_dna_s1", kpId: "g_dna_03", type: .shortAnswer,
                 stem: "某双链 DNA 中腺嘌呤（A）占全部碱基的 30%，求鸟嘌呤（G）所占的比例，并写出依据。",
                 explanation: "依据碱基互补配对 A=T、G=C。",
                 modelAnswer: "双链 DNA 中 A=T、G=C。A 占 30%，则 T 也占 30%，A+T = 60%，所以 G+C = 40%，G=C=20%。",
                 scorePoints: ["A=T=30%", "A+T=60%、G+C=40%", "G=C=20%"]),
        Question(id: "q_dna_c2", kpId: "g_dna_02", type: .choice,
                 stem: "DNA 分子两条链之间的碱基配对遵循的规律是？",
                 explanation: "碱基互补配对：A 与 T 配对（2 个氢键）、G 与 C 配对（3 个氢键）。",
                 options: ["A 与 T 配对、G 与 C 配对", "A 与 G 配对、T 与 C 配对", "A 与 C 配对、T 与 G 配对", "碱基随机配对"],
                 answerIndex: 0),
        Question(id: "q_dna_c3", kpId: "g_dna_03", type: .choice,
                 stem: "在双链 DNA 分子中，下列比值一定等于 1 的是？",
                 explanation: "双链中嘌呤总数=嘧啶总数，即 A+G=T+C，故 (A+G)/(T+C)=1；A/G、(A+T)/(G+C) 不一定为 1。",
                 options: ["(A+G)/(T+C)", "A/G", "(A+T)/(G+C)", "A/C"],
                 answerIndex: 0),
    ]

    // 可遗传变异
    private static let variation: [Question] = [
        Question(id: "q_var_c1", kpId: "g_var_01", type: .choice,
                 stem: "下列关于可遗传变异的叙述，正确的是？",
                 explanation: "基因突变产生新基因、是变异的根本来源；基因重组不产生新基因，只重新组合已有基因，是有性生殖中多样性的主要来源。",
                 options: ["基因突变能产生新基因", "基因重组能产生新基因", "染色体变异不属于可遗传变异", "基因突变只发生在减数分裂时"],
                 answerIndex: 0),
        Question(id: "q_var_c2", kpId: "g_var_01", type: .choice,
                 stem: "下列变异中，属于基因重组的是？",
                 explanation: "基因重组发生在减数分裂：非同源染色体上非等位基因自由组合、四分体时期同源染色体非姐妹染色单体交叉互换。",
                 options: ["减数分裂时非等位基因自由组合", "一个碱基对被替换", "染色体缺失一段", "染色体数目增加一倍"],
                 answerIndex: 0),
    ]

    // 现代生物进化理论 + 基因频率
    private static let evolution: [Question] = [
        Question(id: "q_evo_c1", kpId: "g_evo_01", type: .choice,
                 stem: "现代生物进化理论认为，进化的基本单位和决定进化方向的因素分别是？",
                 explanation: "种群是生物进化的基本单位；突变和基因重组提供原材料；自然选择使种群基因频率定向改变，决定进化方向。",
                 options: ["种群；自然选择", "个体；基因突变", "物种；地理隔离", "种群；基因重组"],
                 answerIndex: 0),
        Question(id: "q_evo_s1", kpId: "g_evo_02", type: .shortAnswer,
                 stem: "某动物种群中，基因型 AA 占 30%、Aa 占 60%、aa 占 10%。求 A 和 a 的基因频率。",
                 explanation: "基因频率 = 该基因数 / 等位基因总数，可用基因型频率换算。",
                 modelAnswer: "A 的频率 = AA% + 1/2·Aa% = 30% + 1/2×60% = 60%；a 的频率 = aa% + 1/2·Aa% = 10% + 30% = 40%（或 1−60%=40%）。",
                 scorePoints: ["A% = AA% + ½Aa%", "A 频率 = 60%", "a 频率 = 40%"]),
        Question(id: "q_evo_c2", kpId: "g_evo_01", type: .choice,
                 stem: "现代生物进化理论认为，生物进化的实质是？",
                 explanation: "进化的实质是种群基因频率的改变；自然选择使基因频率定向改变。",
                 options: ["种群基因频率的改变", "个体表现型的改变", "新物种的产生", "基因型频率的改变"],
                 answerIndex: 0),
        Question(id: "q_evo_c3", kpId: "g_evo_02", type: .choice,
                 stem: "某遗传平衡的种群中，隐性纯合子（aa）占 16%，则 a 基因的频率是？",
                 explanation: "遗传平衡下 aa = q² = 0.16，开平方得 q（a 频率）= 0.4。",
                 options: ["0.4", "0.16", "0.6", "0.84"],
                 answerIndex: 0),
    ]

    // 内环境与稳态
    private static let internalEnv: [Question] = [
        Question(id: "q_env_c1", kpId: "h_env_01", type: .choice,
                 stem: "人体内环境主要包括？",
                 explanation: "内环境（细胞外液）主要由血浆、组织液和淋巴组成，是体内细胞直接生活的液体环境。",
                 options: ["血浆、组织液和淋巴", "血液、组织液和细胞内液", "血浆、细胞内液和淋巴", "消化液、血浆和组织液"],
                 answerIndex: 0),
        Question(id: "q_env_s1", kpId: "h_env_01", type: .shortAnswer,
                 stem: "什么是内环境稳态？维持稳态的主要调节机制是什么？",
                 explanation: "答动态平衡与神经—体液—免疫调节网络。",
                 modelAnswer: "稳态是指正常机体通过调节作用，使各器官、系统协调活动，共同维持内环境的相对稳定状态；内环境的化学成分和理化性质（如温度、pH、渗透压）保持动态平衡。其主要调节机制是神经—体液—免疫调节网络。",
                 scorePoints: ["内环境（化学成分和理化性质）保持相对稳定/动态平衡", "由各器官系统协调活动维持", "神经—体液—免疫调节网络"]),
    ]

    // 兴奋的产生与传导
    private static let nerve: [Question] = [
        Question(id: "q_ner_c1", kpId: "h_nerve_01", type: .choice,
                 stem: "神经纤维受刺激产生兴奋时，膜电位变化和离子流动是？",
                 explanation: "静息电位外正内负（K⁺外流维持）；受刺激时 Na⁺内流，使该处变为外负内正（动作电位）。",
                 options: ["Na⁺ 内流，膜电位变为外负内正", "K⁺ 内流，膜电位外正内负", "Na⁺ 外流，膜电位外正内负", "Cl⁻ 内流，膜电位不变"],
                 answerIndex: 0),
        Question(id: "q_ner_c2", kpId: "h_nerve_01", type: .choice,
                 stem: "兴奋在神经纤维上和在突触处的传导/传递方向分别是？",
                 explanation: "在神经纤维上可双向传导；在突触处由于神经递质只能由突触前膜释放、作用于突触后膜，只能单向传递。",
                 options: ["纤维上双向、突触处单向", "都双向", "都单向", "纤维上单向、突触处双向"],
                 answerIndex: 0),
    ]

    // 特异性免疫
    private static let immune: [Question] = [
        Question(id: "q_imm_c1", kpId: "h_immune_01", type: .choice,
                 stem: "在体液免疫中，能产生并分泌抗体的细胞是？",
                 explanation: "B 细胞增殖分化形成浆细胞（效应 B 细胞），由浆细胞产生抗体；浆细胞本身不能识别抗原。",
                 options: ["浆细胞", "细胞毒性 T 细胞", "记忆细胞", "吞噬细胞"],
                 answerIndex: 0),
        Question(id: "q_imm_s1", kpId: "h_immune_01", type: .shortAnswer,
                 stem: "为什么同种病原体第二次侵入机体时，往往不会患病？（用记忆细胞解释）",
                 explanation: "考查二次免疫应答的特点。",
                 modelAnswer: "机体第一次接触某种抗原后，会产生相应的记忆细胞。当同种抗原再次侵入时，记忆细胞能迅速增殖分化，快速产生大量浆细胞和抗体（或细胞毒性 T 细胞），使免疫反应比第一次更快、更强，往往在患病前就将病原体清除，因此不会患病。",
                 scorePoints: ["第一次免疫产生记忆细胞", "记忆细胞再次接触抗原迅速增殖分化", "更快更强地产生抗体（效应细胞）", "在患病前清除病原体"]),
    ]

    // 种群数量变化
    private static let population: [Question] = [
        Question(id: "q_pop_c1", kpId: "e_pop_01", type: .choice,
                 stem: "关于种群“S”形增长的叙述，正确的是？",
                 explanation: "S 形增长中存在环境容纳量 K，种群增长速率在 K/2 时最大，达到 K 后趋于稳定。",
                 options: ["种群增长速率在 K/2 时最大", "K 值固定不变", "增长率始终保持不变", "达到 K 值后种群数量持续上升"],
                 answerIndex: 0),
        Question(id: "q_pop_s1", kpId: "e_pop_01", type: .shortAnswer,
                 stem: "对家鼠等有害动物进行防治时，应从控制 K 值角度采取什么措施？为什么？灭鼠后为何数量易回升？",
                 explanation: "从降低环境容纳量、K/2 增长最快两方面答。",
                 modelAnswer: "应采取断绝食物来源、搞好环境卫生、清除杂物等措施，降低环境容纳量（K 值），从而减少家鼠数量。若仅靠捕杀使数量降到 K/2 附近，此时增长速率最大，种群数量会很快回升，故单纯捕杀效果有限，关键是降低 K 值。",
                 scorePoints: ["降低环境容纳量 K（断绝食物、改善环境卫生）", "K/2 时增长速率最大", "数量降到 K/2 附近会快速回升"]),
    ]

    // 能量流动 + 能量计算
    private static let energyFlow: [Question] = [
        Question(id: "q_ef_c1", kpId: "e_eco_02", type: .choice,
                 stem: "生态系统能量流动的特点是？",
                 explanation: "能量流动是单向流动、逐级递减的，相邻营养级间传递效率约为 10%~20%，不能循环利用。",
                 options: ["单向流动、逐级递减", "循环流动、逐级递减", "单向流动、逐级递增", "双向流动、保持不变"],
                 answerIndex: 0),
        Question(id: "q_ef_s1", kpId: "e_eco_05", type: .shortAnswer,
                 stem: "食物链：草→兔→狐。若狐要增重 1 kg，最多和最少需消耗草各多少 kg？写出推算。",
                 explanation: "最多用最低效率 10% 反推、最少用最高效率 20% 反推。",
                 modelAnswer: "最多消耗草：按 10% 传递效率反推，1÷10%÷10% = 100 kg；最少消耗草：按 20% 传递效率反推，1÷20%÷20% = 25 kg。所以最多需 100 kg、最少需 25 kg 草。",
                 scorePoints: ["最多按 10% 反推", "最多 = 1÷10%÷10% = 100 kg", "最少按 20% 反推 = 25 kg"]),
        Question(id: "q_ef_c2", kpId: "e_eco_02", type: .choice,
                 stem: "生态系统中能量流动的渠道（途径）是？",
                 explanation: "能量沿食物链和食物网逐级流动，食物链（网）是能量流动和物质循环的渠道。",
                 options: ["食物链和食物网", "种群", "分解者", "大气环流"],
                 answerIndex: 0),
        Question(id: "q_ef_c3", kpId: "e_eco_05", type: .choice,
                 stem: "食物链「草→兔→狐」中，若草固定的能量为 10000 kJ，狐最多能获得的能量约为？",
                 explanation: "求‘最多’用最高传递效率 20%：10000×20%×20% = 400 kJ。",
                 options: ["400 kJ", "1000 kJ", "100 kJ", "2000 kJ"],
                 answerIndex: 0),
    ]

    // 碳循环
    private static let carbonCycle: [Question] = [
        Question(id: "q_carb_c1", kpId: "e_eco_07", type: .choice,
                 stem: "碳在生物群落与无机环境之间循环的主要形式是？",
                 explanation: "碳在生物群落与无机环境之间主要以 CO₂ 形式循环；在生物群落内部以含碳有机物的形式沿食物链传递。",
                 options: ["CO₂", "碳酸盐", "含碳有机物", "一氧化碳"],
                 answerIndex: 0),
        Question(id: "q_carb_s1", kpId: "e_eco_07", type: .shortAnswer,
                 stem: "大气中 CO₂ 增多会引起温室效应。请从碳循环角度说明 CO₂ 增多的主要原因及缓解措施。",
                 explanation: "从化石燃料燃烧、植被破坏与对应措施作答。",
                 modelAnswer: "主要原因：人类大量燃烧煤、石油等化石燃料，短时间内释放大量 CO₂；同时大面积破坏森林植被使绿色植物对 CO₂ 的固定（光合作用）减少，打破了碳循环的平衡。缓解措施：减少化石燃料的燃烧、开发清洁能源，大力植树造林、保护植被，增加对 CO₂ 的固定。",
                 scorePoints: ["化石燃料大量燃烧释放 CO₂", "植被破坏使光合固定 CO₂ 减少", "减少化石燃料燃烧/用清洁能源", "植树造林增加 CO₂ 的固定"]),
    ]

    // 生态系统稳定性
    private static let stability: [Question] = [
        Question(id: "q_stab_c1", kpId: "e_eco_09", type: .choice,
                 stem: "下列关于生态系统稳定性的叙述，正确的是？",
                 explanation: "营养结构越复杂、物种越多，自我调节能力越强，抵抗力稳定性越高；负反馈调节是自我调节能力的基础。",
                 options: ["生态系统成分越复杂，抵抗力稳定性越高", "抵抗力稳定性与恢复力稳定性总是同时增强", "热带雨林的恢复力稳定性比草原高", "负反馈调节会使生态系统失衡"],
                 answerIndex: 0),
        Question(id: "q_stab_c2", kpId: "e_eco_09", type: .choice,
                 stem: "生态系统自我调节能力的基础是？",
                 explanation: "负反馈调节在生态系统中普遍存在，是生态系统自我调节能力的基础。",
                 options: ["负反馈调节", "正反馈调节", "能量逐级递减", "物质循环"],
                 answerIndex: 0),
    ]

    // 基因工程
    private static let geneEng: [Question] = [
        Question(id: "q_ge_c1", kpId: "b_gene_01", type: .choice,
                 stem: "基因工程中，被称为“分子手术刀”和“分子缝合针”的工具分别是？",
                 explanation: "限制（性核酸内切）酶切割特定序列，是“分子手术刀”；DNA 连接酶连接黏性末端，是“分子缝合针”；载体是运输工具。",
                 options: ["限制酶；DNA 连接酶", "DNA 连接酶；限制酶", "限制酶；运载体", "DNA 聚合酶；限制酶"],
                 answerIndex: 0),
        Question(id: "q_ge_s1", kpId: "b_gene_01", type: .shortAnswer,
                 stem: "写出基因工程操作的四个基本步骤。",
                 explanation: "考查基因工程的基本流程。",
                 modelAnswer: "①获取目的基因；②构建基因表达载体（核心步骤）；③将目的基因导入受体细胞；④检测与鉴定（目的基因是否导入、是否表达等）。",
                 scorePoints: ["获取目的基因", "构建基因表达载体（核心）", "导入受体细胞", "检测与鉴定"]),
    ]

    // 初中：光合作用
    private static let cellJunior: [Question] = [
        Question(id: "q_jpho_c1", kpId: "j_plant_01", type: .choice,
                 stem: "绿色植物光合作用的场所、原料和产物分别是？",
                 explanation: "光合作用在叶绿体中进行，以 CO₂ 和水为原料，在光下合成有机物（储存能量）并释放 O₂。",
                 options: ["叶绿体；二氧化碳和水；有机物和氧气", "线粒体；氧气和有机物；二氧化碳和水", "叶绿体；氧气和水；有机物", "细胞核；二氧化碳；氧气"],
                 answerIndex: 0),
        Question(id: "q_jpho_s1", kpId: "j_plant_01", type: .shortAnswer,
                 stem: "用文字写出绿色植物光合作用的反应概况（含场所、条件）。",
                 explanation: "考查光合作用的文字表达式与条件。",
                 modelAnswer: "二氧化碳 + 水 —（光、叶绿体）→ 有机物（储存能量）+ 氧气。光合作用在叶绿体中进行，必须在光下才能完成，把无机物制造成有机物并把光能转变为化学能储存起来。",
                 scorePoints: ["原料：二氧化碳和水", "条件：光、叶绿体", "产物：有机物（储能）和氧气"]),
    ]

    // 初中：血液循环
    private static let circulation: [Question] = [
        Question(id: "q_circ_c1", kpId: "j_human_02", type: .choice,
                 stem: "关于人体血液循环的叙述，正确的是？",
                 explanation: "体循环：左心室→主动脉→全身→上下腔静脉→右心房；肺循环：右心室→肺动脉→肺→肺静脉→左心房。肺动脉里流的是静脉血。",
                 options: ["体循环起点是左心室", "肺循环起点是左心室", "动脉中一定流动脉血", "肺动脉中流动脉血"],
                 answerIndex: 0),
        Question(id: "q_circ_c2", kpId: "j_human_02", type: .choice,
                 stem: "血液流经肺部毛细血管后，血液成分变化是？",
                 explanation: "经过肺循环，血液在肺部进行气体交换，吸收 O₂、排出 CO₂，由静脉血变成动脉血。",
                 options: ["由静脉血变成动脉血", "由动脉血变成静脉血", "含氧量减少", "二氧化碳增多"],
                 answerIndex: 0),
    ]

    // MARK: 付费内容 · 突触与神经递质（选必1 高频）
    private static let nerveSynapse: [Question] = [
        Question(id: "q_syn_c1", kpId: "h_nerve_02", type: .choice,
                 stem: "神经递质从突触前膜释放到突触间隙的方式是？",
                 explanation: "神经递质以突触小泡形式经胞吐释放，体现细胞膜的流动性，需要消耗能量。",
                 options: ["主动运输", "协助扩散", "胞吐（消耗能量、体现膜的流动性）", "自由扩散"],
                 answerIndex: 2),
        Question(id: "q_syn_c2", kpId: "h_nerve_02", type: .choice,
                 stem: "关于兴奋在突触处的传递，正确的是？",
                 explanation: "神经递质只能由突触前膜释放、作用于突触后膜，所以兴奋在突触处只能单向传递。",
                 options: ["可以双向传递", "只能由突触前膜传向突触后膜（单向）", "由突触后膜释放递质", "传递速度比在神经纤维上更快"],
                 answerIndex: 1),
    ]

    // MARK: 付费内容 · 物质循环（选必2 高频）
    private static let materialCycle: [Question] = [
        Question(id: "q_cyc_c1", kpId: "e_eco_03", type: .choice,
                 stem: "与能量流动相比，生态系统物质循环的特点是？",
                 explanation: "物质循环具有全球性、可反复循环利用；能量流动则是单向流动、逐级递减、不可循环。",
                 options: ["单向流动", "逐级递减", "只在局部生态系统内进行", "具全球性，可反复循环利用"],
                 answerIndex: 3),
        Question(id: "q_cyc_c2", kpId: "e_eco_03", type: .choice,
                 stem: "关于物质循环与能量流动的关系，正确的是？",
                 explanation: "二者同时进行、相互依存：物质是能量的载体，能量是物质循环的动力。",
                 options: ["二者同时进行、相互依存，物质是能量的载体", "物质循环不需要能量驱动", "能量也能像物质一样被反复循环利用", "二者彼此独立、互不相关"],
                 answerIndex: 0),
    ]

    // MARK: 付费内容 · 必修2 遗传与进化（高频 weight=2 补题）
    private static let geneticsMore: [Question] = [
        Question(id: "q_gm2_c1", kpId: "g_meiosis_02", type: .choice,
                 stem: "减数分裂过程中，能增加配子种类（多样性）的是？",
                 explanation: "减Ⅰ后期非同源染色体自由组合、四分体时期同源染色体非姐妹染色单体间的交叉互换，都使配子种类增多。",
                 options: ["DNA 的复制", "姐妹染色单体的分开", "非同源染色体自由组合和四分体时期的交叉互换", "着丝点的分裂"],
                 answerIndex: 2),
        Question(id: "q_md3_c1", kpId: "g_mendel_03", type: .choice,
                 stem: "某性状正交与反交的结果不同，最可能说明该基因位于？",
                 explanation: "正反交结果不同，常提示基因位于 X 染色体上（伴性遗传）或在细胞质中（细胞质遗传）。",
                 options: ["常染色体上", "X 染色体上或细胞质中", "Y 染色体上", "与位置无关"],
                 answerIndex: 1),
        Question(id: "q_dna1_c1", kpId: "g_dna_01", type: .choice,
                 stem: "噬菌体侵染细菌实验中，用放射性同位素 ³²P 标记的是噬菌体的？",
                 explanation: "P 是 DNA 特有元素，³²P 标记 DNA；S 是蛋白质特有元素，³⁵S 标记蛋白质外壳。",
                 options: ["蛋白质外壳", "核糖体", "磷脂", "DNA"],
                 answerIndex: 3),
        Question(id: "q_ex2_c1", kpId: "g_expr_02", type: .choice,
                 stem: "关于密码子，下列叙述正确的是？",
                 explanation: "密码子共 64 种，其中 3 种是终止密码子不编码氨基酸，其余 61 种编码氨基酸；密码子位于 mRNA 上。",
                 options: ["共 20 种", "都能编码氨基酸", "共 64 种，其中 3 种是终止密码子不编码氨基酸", "位于 tRNA 上"],
                 answerIndex: 2),
        Question(id: "q_var2_c1", kpId: "g_var_02", type: .choice,
                 stem: "下列不属于基因突变特点的是？",
                 explanation: "基因突变具普遍性、随机性、低频性、不定向性、多害少利性；它是不定向的，没有“定向性”。",
                 options: ["定向性", "随机性", "低频性", "普遍性"],
                 answerIndex: 0),
        Question(id: "q_brd_c1", kpId: "g_breed_01", type: .choice,
                 stem: "下列育种方法中，能明显缩短育种年限的是？",
                 explanation: "单倍体育种（花药离体培养 + 秋水仙素诱导加倍）能明显缩短育种年限。",
                 options: ["杂交育种", "诱变育种", "多倍体育种", "单倍体育种（花药离体培养后人工诱导加倍）"],
                 answerIndex: 3),
        Question(id: "q_evo3_c1", kpId: "g_evo_03", type: .choice,
                 stem: "新物种形成的标志是？",
                 explanation: "生殖隔离是新物种形成的标志；地理隔离不一定导致生殖隔离。",
                 options: ["出现地理隔离", "出现生殖隔离", "基因频率发生改变", "表现型发生改变"],
                 answerIndex: 1),
        Question(id: "q_fg_c1", kpId: "g_freq_genotype", type: .choice,
                 stem: "杂合子（Aa）连续自交，后代种群中？",
                 explanation: "自交使杂合子每代减半、纯合子增多，基因型频率改变；但基因频率不变。",
                 options: ["基因频率不断改变", "纯合子比例下降", "杂合子比例下降、纯合子比例上升，但基因频率不变", "基因型频率保持不变"],
                 answerIndex: 2),
        Question(id: "q_dis_c1", kpId: "g_disease", type: .choice,
                 stem: "21 三体综合征（先天愚型）属于？",
                 explanation: "21 三体综合征是 21 号染色体多一条，属于染色体（数目）异常遗传病。",
                 options: ["单基因遗传病", "染色体异常遗传病", "多基因遗传病", "传染病"],
                 answerIndex: 1),
        Question(id: "q_911_c1", kpId: "g_911", type: .choice,
                 stem: "两对独立遗传的基因，F₂ 出现 9∶7 的性状比，其本质遵循？",
                 explanation: "9∶7 是 9∶3∶3∶1 的变式（基因互作），本质仍是基因的自由组合定律。",
                 options: ["分离定律", "连锁与互换定律", "细胞质遗传", "自由组合定律（基因互作的结果）"],
                 answerIndex: 3),
    ]

    // MARK: 付费内容 · 选必1 稳态与调节（高频 weight=2 补题）
    private static let homeostasisMore: [Question] = [
        Question(id: "q_env2_c1", kpId: "h_env_02", type: .choice,
                 stem: "正常人血浆的 pH 能稳定在 7.35~7.45，主要依靠？",
                 explanation: "血浆中的缓冲物质（如 NaHCO₃/H₂CO₃）能中和酸碱，维持 pH 相对稳定。",
                 options: ["大量饮水", "抗利尿激素", "血浆中的缓冲物质（如 NaHCO₃/H₂CO₃）", "胰岛素"],
                 answerIndex: 2),
        Question(id: "q_env3_c1", kpId: "h_env_03", type: .choice,
                 stem: "长期营养不良引起组织水肿，其直接原因是？",
                 explanation: "营养不良使血浆蛋白减少，血浆渗透压降低，组织液回流减少，导致组织水肿。",
                 options: ["血浆蛋白减少，血浆渗透压降低", "组织液减少", "红细胞数目增多", "血糖浓度升高"],
                 answerIndex: 0),
        Question(id: "q_hm2_c1", kpId: "h_humor_02", type: .choice,
                 stem: "人体体温调节的中枢位于？",
                 explanation: "体温调节中枢位于下丘脑；大脑皮层产生冷热感觉。",
                 options: ["大脑皮层", "下丘脑", "小脑", "脊髓"],
                 answerIndex: 1),
        Question(id: "q_hm5_c1", kpId: "h_humor_05", type: .choice,
                 stem: "甲状腺激素分泌的分级调节，其调节顺序是？",
                 explanation: "下丘脑分泌促甲状腺激素释放激素(TRH)→垂体分泌促甲状腺激素(TSH)→甲状腺分泌甲状腺激素。",
                 options: ["垂体 → 下丘脑 → 甲状腺", "甲状腺 → 垂体 → 下丘脑", "下丘脑 → 甲状腺 → 垂体", "下丘脑 → 垂体 → 甲状腺"],
                 answerIndex: 3),
        Question(id: "q_nr3_c1", kpId: "h_nerve_03", type: .choice,
                 stem: "完成反射活动的结构基础是？",
                 explanation: "反射活动必须依赖完整的反射弧，任一环节受损反射都不能完成。",
                 options: ["大脑皮层", "单个神经元", "完整的反射弧", "脊髓"],
                 answerIndex: 2),
        Question(id: "q_im2_c1", kpId: "h_immune_02", type: .choice,
                 stem: "免疫系统的三大基本功能是？",
                 explanation: "免疫系统具有免疫防御、免疫自稳、免疫监视三大功能。",
                 options: ["免疫防御、免疫自稳、免疫监视", "呼吸、消化、循环", "支持、连接、保护", "调节血糖、血压、体温"],
                 answerIndex: 0),
        Question(id: "q_im3_c1", kpId: "h_immune_03", type: .choice,
                 stem: "下列关于过敏反应的叙述，正确的是？",
                 explanation: "过敏反应是已免疫的机体再次接触相同过敏原时所发生的反应，特点是发作迅速、消退较快。",
                 options: ["第一次接触过敏原时就发生", "已免疫的机体再次接触相同过敏原时发生", "由免疫功能缺陷引起", "由病原体直接破坏细胞引起"],
                 answerIndex: 1),
        Question(id: "q_im6_c1", kpId: "h_immune_06", type: .choice,
                 stem: "HIV（艾滋病病毒）主要攻击人体的？",
                 explanation: "HIV 主要攻击辅助性 T 细胞，使人体免疫功能几乎丧失。",
                 options: ["红细胞", "浆细胞", "肝细胞", "辅助性 T 细胞"],
                 answerIndex: 3),
        Question(id: "q_pl1_c1", kpId: "h_plant_01", type: .choice,
                 stem: "生长素的极性运输是指？",
                 explanation: "极性运输是主动运输，只能从形态学上端运向形态学下端，不能逆向。",
                 options: ["只能从形态学上端运向形态学下端", "只能从形态学下端运向上端", "可以双向自由运输", "通过自由扩散、不消耗能量"],
                 answerIndex: 0),
        Question(id: "q_pl4_c1", kpId: "h_plant_04", type: .choice,
                 stem: "不同器官对生长素的敏感程度由高到低正确的是？",
                 explanation: "敏感程度：根 > 芽 > 茎，故同一浓度可能促进茎而抑制根。",
                 options: ["茎 > 芽 > 根", "芽 > 根 > 茎", "根 > 芽 > 茎", "三者敏感程度相同"],
                 answerIndex: 2),
    ]

    // MARK: 付费内容 · 选必2 生物与环境（高频 weight=2 补题）
    private static let ecologyMore: [Question] = [
        Question(id: "q_ec1_c1", kpId: "e_eco_01", type: .choice,
                 stem: "生态系统中，分解者的主要作用是？",
                 explanation: "分解者把动植物遗体、排泄物中的有机物分解为无机物，归还到无机环境。",
                 options: ["固定太阳能制造有机物", "把有机物分解为无机物归还无机环境", "以现成的有机物为食并捕食其他动物", "为生态系统提供最初的能量来源"],
                 answerIndex: 1),
        Question(id: "q_ec4_c1", kpId: "e_eco_04", type: .choice,
                 stem: "孔雀开屏、蜜蜂跳舞传递信息，属于哪一类信息？",
                 explanation: "通过动物的特殊行为传递的信息属于行为信息。",
                 options: ["物理信息", "化学信息", "行为信息", "营养信息"],
                 answerIndex: 2),
        Question(id: "q_ec6_c1", kpId: "e_eco_06", type: .choice,
                 stem: "研究生态系统能量流动的实践意义在于？",
                 explanation: "研究能量流动可帮助人类合理调整能量流动关系，使能量持续高效地流向对人类最有益的部分。",
                 options: ["合理调整能量流动关系，使能量持续高效流向对人类最有益的部分", "让能量在生态系统中循环利用", "把能量传递效率提高到 100%", "彻底消灭所有天敌"],
                 answerIndex: 0),
        Question(id: "q_cm1_c1", kpId: "e_comm_01", type: .choice,
                 stem: "弃耕的农田上发生的群落演替属于？",
                 explanation: "弃耕农田保留了原有土壤条件和繁殖体，属于次生演替。",
                 options: ["初生演替", "次生演替", "不发生演替", "原生演替"],
                 answerIndex: 1),
        Question(id: "q_cm2_c1", kpId: "e_comm_02", type: .choice,
                 stem: "大豆与其根部根瘤菌之间的种间关系是？",
                 explanation: "根瘤菌为大豆提供含氮养料，大豆为根瘤菌提供有机养料，属互利共生。",
                 options: ["寄生", "竞争", "捕食", "互利共生"],
                 answerIndex: 3),
        Question(id: "q_pop2_c1", kpId: "e_pop_02", type: .choice,
                 stem: "能预测种群数量变化趋势的种群特征是？",
                 explanation: "年龄组成（增长型/稳定型/衰退型）能预测种群数量的未来变化趋势。",
                 options: ["年龄组成", "种群密度", "性别比例", "出生率"],
                 answerIndex: 0),
        Question(id: "q_pop3_c1", kpId: "e_pop_03", type: .choice,
                 stem: "调查农田中田鼠的种群密度，宜采用的方法是？",
                 explanation: "田鼠活动能力强、活动范围大，宜用标志重捕法；样方法适用于植物和活动范围小的动物。",
                 options: ["样方法", "记名计算法", "标志重捕法", "抽样检测法"],
                 answerIndex: 2),
        Question(id: "q_pro1_c1", kpId: "e_protect_01", type: .choice,
                 stem: "保护生物多样性最有效的措施是？",
                 explanation: "就地保护（建立自然保护区等）是对生物多样性最有效的保护措施。",
                 options: ["易地（迁地）保护", "就地保护（建立自然保护区）", "建立基因库", "制定保护法律法规"],
                 answerIndex: 1),
    ]

    // MARK: 付费内容 · 选必3 生物技术与工程（高频 weight=2 补题）
    private static let biotechMore: [Question] = [
        Question(id: "q_pcr_c1", kpId: "b_pcr", type: .choice,
                 stem: "PCR 技术中，需要用到的耐高温的酶是？",
                 explanation: "PCR 用加热变性代替解旋酶，需要耐高温的热稳定 DNA 聚合酶（Taq 酶）。",
                 options: ["解旋酶", "DNA 连接酶", "热稳定 DNA 聚合酶（Taq 酶）", "限制酶"],
                 answerIndex: 2),
        Question(id: "q_trad_c1", kpId: "b_traditional", type: .choice,
                 stem: "制作果酒和果醋分别主要利用的微生物是？",
                 explanation: "果酒用酵母菌（无氧发酵），果醋用醋酸菌（有氧发酵）。",
                 options: ["酵母菌、醋酸菌", "乳酸菌、毛霉", "醋酸菌、酵母菌", "毛霉、乳酸菌"],
                 answerIndex: 0),
        Question(id: "q_med_c1", kpId: "b_medium", type: .choice,
                 stem: "培养微生物时，对培养基最常用的灭菌方法是？",
                 explanation: "培养基常用高压蒸汽灭菌，可彻底杀灭所有微生物（包括芽孢）。",
                 options: ["巴氏消毒法", "煮沸消毒", "紫外线消毒", "高压蒸汽灭菌"],
                 answerIndex: 3),
        Question(id: "q_mab_c1", kpId: "b_mab", type: .choice,
                 stem: "制备单克隆抗体时，与经免疫的 B 淋巴细胞融合的细胞是？",
                 explanation: "B 淋巴细胞与骨髓瘤细胞融合形成杂交瘤细胞，既能无限增殖又能产生特异性抗体。",
                 options: ["效应 T 细胞", "骨髓瘤细胞", "浆细胞", "红细胞"],
                 answerIndex: 1),
        Question(id: "q_pcl_c1", kpId: "b_cell_01", type: .choice,
                 stem: "植物组织培养技术所依据的生物学原理是？",
                 explanation: "植物组织培养依据细胞的全能性，经脱分化、再分化发育成完整植株。",
                 options: ["基因重组", "细胞分化", "细胞的全能性", "细胞膜的流动性"],
                 answerIndex: 2),
    ]

    // MARK: 付费内容 · 必修2 配题补满（覆盖率拉满）
    private static let geneticsFill: [Question] = [
        Question(id: "q_fert_c1", kpId: "g_fert", type: .choice,
                 stem: "减数分裂和受精作用对生物遗传的重要意义是？",
                 explanation: "减数分裂使配子染色体减半，受精作用使其恢复，二者共同维持前后代体细胞染色体数目的恒定。",
                 options: ["只有受精作用维持染色体数恒定", "二者共同维持前后代体细胞染色体数目的恒定", "使染色体数目逐代加倍", "使染色体数目逐代减半"],
                 answerIndex: 1),
        Question(id: "q_method_c1", kpId: "g_method", type: .choice,
                 stem: "孟德尔发现遗传两大定律所运用的科学方法是？",
                 explanation: "孟德尔运用假说—演绎法：发现问题→提出假说→演绎推理（测交预测）→实验验证。",
                 options: ["类比推理法", "同位素标记法", "假说—演绎法", "建立物理模型法"],
                 answerIndex: 2),
        Question(id: "q_dom_c1", kpId: "g_dominance", type: .choice,
                 stem: "具有一对相对性状的纯合亲本杂交，F₁ 表现出来的性状称为？",
                 explanation: "纯合亲本杂交，F₁ 显现的是显性性状；F₁ 自交后代分离出的较少一类是隐性性状。",
                 options: ["显性性状", "隐性性状", "中间性状", "相对性状"],
                 answerIndex: 0),
        Question(id: "q_mon_c1", kpId: "g_monitor", type: .choice,
                 stem: "预防人类遗传病的主要手段是？",
                 explanation: "遗传咨询和产前诊断是监测和预防遗传病的主要手段；近亲结婚会升高隐性遗传病风险。",
                 options: ["多吃营养品", "加强体育锻炼", "注射疫苗", "遗传咨询和产前诊断"],
                 answerIndex: 3),
        Question(id: "q_sic_c1", kpId: "g_sickle", type: .choice,
                 stem: "镰刀型细胞贫血症的根本原因是？",
                 explanation: "基因中一个碱基对被替换，使血红蛋白一个氨基酸改变，属于基因突变。",
                 options: ["染色体数目增多", "基因中一个碱基对的替换（基因突变）", "环境温度过高", "营养不良"],
                 answerIndex: 1),
        Question(id: "q_cnum_c1", kpId: "g_chrom_num", type: .choice,
                 stem: "与二倍体相比，多倍体植株一般具有的特点是？",
                 explanation: "多倍体茎秆粗壮，果实、种子较大，营养物质含量高，但发育延迟、结实率低。",
                 options: ["植株矮小", "完全不能繁殖", "茎秆粗壮，果实、种子较大，营养物质含量高", "性状与二倍体完全相同"],
                 answerIndex: 2),
        Question(id: "q_hap_c1", kpId: "g_haploid", type: .choice,
                 stem: "秋水仙素能诱导染色体数目加倍，其作用原理是？",
                 explanation: "秋水仙素抑制纺锤体的形成，使复制后的染色体不能移向两极，从而引起数目加倍。",
                 options: ["抑制纺锤体的形成", "促进 DNA 复制", "抑制着丝点分裂", "促进同源染色体联会"],
                 answerIndex: 0),
        Question(id: "q_cstr_c1", kpId: "g_chrom_struct", type: .choice,
                 stem: "人类的猫叫综合征是由于第 5 号染色体发生了？",
                 explanation: "猫叫综合征是 5 号染色体部分缺失引起的染色体结构变异。",
                 options: ["数目增加一条", "整条丢失", "基因突变", "部分缺失"],
                 answerIndex: 3),
        Question(id: "q_coevo_c1", kpId: "g_coevo", type: .choice,
                 stem: "不同物种之间、生物与无机环境之间在相互影响中不断进化发展，这称为？",
                 explanation: "协同进化是不同物种之间、生物与无机环境之间相互影响共同进化的过程，生物多样性是其结果。",
                 options: ["自然选择", "协同进化", "地理隔离", "基因重组"],
                 answerIndex: 1),
    ]

    // MARK: 付费内容 · 选必1 配题补满
    private static let homeostasisFill: [Question] = [
        Question(id: "q_hm3_c1", kpId: "h_humor_03", type: .choice,
                 stem: "抗利尿激素的主要作用是？",
                 explanation: "抗利尿激素促进肾小管和集合管对水的重吸收，使尿量减少，从而维持水盐平衡。",
                 options: ["促进排尿、增加尿量", "升高血糖", "促进肾小管和集合管对水的重吸收", "降低体温"],
                 answerIndex: 2),
        Question(id: "q_nr4_c1", kpId: "h_nerve_04", type: .choice,
                 stem: "兴奋在离体神经纤维上的传导方向是？",
                 explanation: "在神经纤维上兴奋可双向传导；只有在突触处因递质单向释放才单向传递。",
                 options: ["双向传导（可向两端传导）", "只能单向传导", "不能传导", "只能传向细胞体"],
                 answerIndex: 0),
        Question(id: "q_hm4_c1", kpId: "h_humor_04", type: .choice,
                 stem: "下列不属于激素调节特点的是？",
                 explanation: "激素调节特点是微量高效、通过体液运输、作用于靶器官靶细胞；激素一经发挥作用即被灭活。",
                 options: ["微量高效", "通过体液运输", "作用于靶器官、靶细胞", "持续起作用、不会被灭活"],
                 answerIndex: 3),
        Question(id: "q_im4_c1", kpId: "h_immune_04", type: .choice,
                 stem: "人体免疫的第三道防线主要由什么组成？",
                 explanation: "第三道防线由免疫器官和免疫细胞组成，属特异性免疫；前两道防线属非特异性免疫。",
                 options: ["皮肤和黏膜", "免疫器官和免疫细胞", "杀菌物质和吞噬细胞", "汗液和泪液"],
                 answerIndex: 1),
        Question(id: "q_im5_c1", kpId: "h_immune_05", type: .choice,
                 stem: "接种疫苗能预防相应疾病，是因为疫苗作为抗原能使机体？",
                 explanation: "疫苗作为抗原引发特异性免疫，使机体产生相应抗体和记忆细胞，再遇病原体可快速清除。",
                 options: ["直接杀死病原体", "增强非特异性免疫", "产生相应的抗体和记忆细胞", "升高体温"],
                 answerIndex: 2),
        Question(id: "q_pl3_c1", kpId: "h_plant_03", type: .choice,
                 stem: "温特把接触过胚芽鞘尖端的琼脂块放在去尖胚芽鞘的一侧，胚芽鞘向对侧弯曲生长。该实验证明？",
                 explanation: "实验证明胚芽鞘尖端产生了某种促进下部生长的物质（后命名为生长素）。",
                 options: ["胚芽鞘尖端产生了促进生长的物质", "尖端能感受单侧光", "生长素能被分解", "光是生长所必需的"],
                 answerIndex: 0),
        Question(id: "q_pl2_c1", kpId: "h_plant_02", type: .choice,
                 stem: "下列植物激素中，能促进果实成熟的是？",
                 explanation: "乙烯促进果实成熟；赤霉素促茎伸长和萌发，脱落酸促休眠和气孔关闭。",
                 options: ["赤霉素", "细胞分裂素", "脱落酸", "乙烯"],
                 answerIndex: 3),
        Question(id: "q_nr5_c1", kpId: "h_nerve_05", type: .choice,
                 stem: "大脑皮层言语区的 S 区（运动性语言中枢）受损，患者会出现？",
                 explanation: "S 区受损导致运动性失语症，患者能看、能听、能写，但不能讲话。",
                 options: ["看不懂文字", "不能讲话（运动性失语症）", "听不见声音", "完全失去记忆"],
                 answerIndex: 1),
        Question(id: "q_pl5_c1", kpId: "h_plant_05", type: .choice,
                 stem: "用适当浓度的生长素类似物处理未受粉的雌蕊，可获得？",
                 explanation: "生长素能促进果实发育，处理未受粉雌蕊可培育出无子果实。",
                 options: ["多倍体植株", "单倍体植株", "无子果实", "转基因植株"],
                 answerIndex: 2),
    ]

    // MARK: 付费内容 · 选必2 配题补满
    private static let ecologyFill: [Question] = [
        Question(id: "q_cm3_c1", kpId: "e_comm_03", type: .choice,
                 stem: "群落中物种数目的多少，称为？",
                 explanation: "物种丰富度指群落中物种数目的多少，是区别不同群落的重要特征。",
                 options: ["物种丰富度", "种群密度", "生态位", "营养级"],
                 answerIndex: 0),
        Question(id: "q_ec8_c1", kpId: "e_eco_08", type: .choice,
                 stem: "利用昆虫性外激素诱捕或干扰害虫交配来防治害虫，利用的是哪类信息？",
                 explanation: "性外激素属化学信息；利用信息传递防治害虫可减少农药污染。",
                 options: ["物理信息", "行为信息", "营养信息", "化学信息"],
                 answerIndex: 3),
        Question(id: "q_ec10_c1", kpId: "e_eco_10", type: .choice,
                 stem: "生态系统中，物质循环和能量流动的关系是？",
                 explanation: "二者同时进行、相互依存：物质是能量流动的载体，能量是物质循环的动力。",
                 options: ["先物质循环再能量流动", "同时进行、相互依存，物质是能量流动的载体", "彼此独立、互不相关", "能量是物质循环的载体"],
                 answerIndex: 1),
        Question(id: "q_pop4_c1", kpId: "e_pop_04", type: .choice,
                 stem: "稻田中水稻个体的空间分布类型属于？",
                 explanation: "人工栽种、株距行距大致相等的水稻属于均匀分布。",
                 options: ["集群分布", "随机分布", "均匀分布", "核心分布"],
                 answerIndex: 2),
        Question(id: "q_pro2_c1", kpId: "e_protect_02", type: .choice,
                 stem: "人类大量燃烧化石燃料，会加剧的全球性环境问题主要是？",
                 explanation: "化石燃料燃烧释放大量 CO₂，加剧全球气候变暖（温室效应）。",
                 options: ["全球气候变暖（温室效应）", "臭氧层空洞", "土地盐碱化", "噪声污染"],
                 answerIndex: 0),
        Question(id: "q_pro3_c1", kpId: "e_protect_03", type: .choice,
                 stem: "“桑基鱼塘”实现物质和能量的多级利用，主要体现了生态工程的哪项原理？",
                 explanation: "桑基鱼塘使废物资源化、物质循环利用，主要体现循环（物质循环再生）原理。",
                 options: ["整体原理", "协调原理", "自生原理", "循环（物质循环再生）原理"],
                 answerIndex: 3),
    ]

    // MARK: 付费内容 · 选必3 配题补满
    private static let biotechFill: [Question] = [
        Question(id: "q_ferm_c1", kpId: "b_ferment_01", type: .choice,
                 stem: "制作果醋时，所用醋酸菌的代谢需要？",
                 explanation: "醋酸菌是需氧型微生物，制醋需供氧（有氧条件）；制果酒的酵母菌则在无氧下发酵。",
                 options: ["无氧条件", "氧气（有氧条件）", "高浓度酒精环境", "低温冷冻"],
                 answerIndex: 1),
        Question(id: "q_cl2_c1", kpId: "b_cell_02", type: .choice,
                 stem: "克隆羊“多莉”的成功（体细胞核移植）证明了？",
                 explanation: "多莉羊证明已高度分化的动物体细胞的细胞核仍具有全能性。",
                 options: ["细胞膜具有流动性", "基因能自由重组", "已分化的动物体细胞核仍具有全能性", "动物细胞能进行光合作用"],
                 answerIndex: 2),
        Question(id: "q_iso_c1", kpId: "b_isolate", type: .choice,
                 stem: "对样品中的活菌进行计数，常用的接种方法是？",
                 explanation: "稀释涂布平板法可统计活菌数（统计值常偏小，因两个以上细胞连在一起只长一个菌落）。",
                 options: ["稀释涂布平板法", "平板划线法", "花药离体培养", "显微镜直接计数全部细胞"],
                 answerIndex: 0),
        Question(id: "q_pcl2_c1", kpId: "b_plant_clone", type: .choice,
                 stem: "进行植物体细胞杂交时，诱导原生质体融合之前必须先去除细胞的？",
                 explanation: "需先用纤维素酶和果胶酶去除细胞壁，获得有活力的原生质体后再诱导融合。",
                 options: ["细胞膜", "细胞核", "线粒体", "细胞壁"],
                 answerIndex: 3),
        Question(id: "q_ac_c1", kpId: "b_animal_culture", type: .choice,
                 stem: "动物细胞培养时，向培养箱通入一定量 CO₂ 的主要作用是？",
                 explanation: "CO₂ 主要用于维持培养液的 pH 稳定。",
                 options: ["供给细胞进行光合作用", "维持培养液的 pH", "作为细胞呼吸的原料", "提供碳源合成有机物"],
                 answerIndex: 1),
        Question(id: "q_emb_c1", kpId: "b_embryo_01", type: .choice,
                 stem: "下列属于胚胎工程技术的是？",
                 explanation: "胚胎移植属胚胎工程；植物组织培养、PCR、平板划线分别属其他技术。",
                 options: ["植物组织培养", "PCR 扩增", "胚胎移植", "平板划线"],
                 answerIndex: 2),
        Question(id: "q_gapp_c1", kpId: "b_gene_app", type: .choice,
                 stem: "下列属于基因工程产品的是？",
                 explanation: "用大肠杆菌（导入人胰岛素基因）生产的人胰岛素是基因工程的典型产品。",
                 options: ["用大肠杆菌生产的人胰岛素", "杂交水稻", "多倍体无子西瓜", "秋水仙素处理得到的多倍体"],
                 answerIndex: 0),
        Question(id: "q_safe_c1", kpId: "b_safety", type: .choice,
                 stem: "目前大多数国家明令禁止的是？",
                 explanation: "出于伦理考虑，多数国家明令禁止生殖性克隆人。",
                 options: ["种植转基因作物", "试管婴儿技术", "细菌发酵生产药物", "生殖性克隆人"],
                 answerIndex: 3),
    ]

    // MARK: 付费内容 · 必修2 高频考点加密（第 2 题，换角度）
    private static let geneticsDense: [Question] = [
        Question(id: "q_dna1_c2", kpId: "g_dna_01", type: .choice,
                 stem: "艾弗里的肺炎双球菌体外转化实验证明，使 R 型细菌转化为 S 型的物质是？",
                 explanation: "艾弗里把 S 型菌的 DNA、蛋白质、多糖分别加入 R 型菌培养，只有 DNA 能使 R 型转化为 S 型，证明 DNA 是遗传物质。",
                 options: ["蛋白质", "DNA", "荚膜多糖", "RNA"],
                 answerIndex: 1),
        Question(id: "q_gm2_c2", kpId: "g_meiosis_02", type: .choice,
                 stem: "同源染色体的非姐妹染色单体之间发生交叉互换，一般发生在？",
                 explanation: "交叉互换发生在减Ⅰ前期的四分体时期，是基因重组的来源之一。",
                 options: ["减Ⅰ前期（四分体时期）", "减Ⅱ后期", "有丝分裂中期", "受精作用时"],
                 answerIndex: 0),
        Question(id: "q_md3_c2", kpId: "g_mendel_03", type: .choice,
                 stem: "测交（与隐性纯合子杂交）的主要用途是？",
                 explanation: "测交后代的表现型及比例能反映被测个体产生的配子种类，可测定显性个体的基因型。",
                 options: ["测定显性个体的基因型", "产生新物种", "提高产量", "改变种群基因频率"],
                 answerIndex: 0),
        Question(id: "q_var2_c2", kpId: "g_var_02", type: .choice,
                 stem: "生物变异的根本（最初）来源是？",
                 explanation: "基因突变能产生新基因，是生物变异的根本来源，也为进化提供原材料。",
                 options: ["基因重组", "基因突变", "染色体变异", "环境改变"],
                 answerIndex: 1),
        Question(id: "q_evo3_c2", kpId: "g_evo_03", type: .choice,
                 stem: "关于隔离与物种形成，下列叙述正确的是？",
                 explanation: "地理隔离不一定导致生殖隔离；只有产生生殖隔离才标志新物种的形成。",
                 options: ["地理隔离一定导致生殖隔离", "地理隔离不一定导致生殖隔离，生殖隔离才标志新物种形成", "没有隔离也能形成新物种", "生殖隔离只是进化的原材料"],
                 answerIndex: 1),
        Question(id: "q_fg_c2", kpId: "g_freq_genotype", type: .choice,
                 stem: "在没有突变、选择、迁移等因素影响时，种群随机交配若干代后，基因频率会？",
                 explanation: "遗传平衡（哈代—温伯格）下，随机交配不改变基因频率，世代保持不变。",
                 options: ["逐代增大", "逐代减小", "保持不变", "下降到 0"],
                 answerIndex: 2),
        Question(id: "q_911_c2", kpId: "g_911", type: .choice,
                 stem: "基因型 AaBb（两对基因独立遗传）的个体，能产生几种配子？",
                 explanation: "n 对杂合产生 2ⁿ 种配子，AaBb 为 2²=4 种：AB、Ab、aB、ab。",
                 options: ["2 种", "4 种", "8 种", "16 种"],
                 answerIndex: 1),
        Question(id: "q_brd_c2", kpId: "g_breed_01", type: .choice,
                 stem: "诱变育种（如太空育种）所依据的遗传学原理主要是？",
                 explanation: "诱变育种利用物理、化学因素诱发基因突变，从中选育优良变异类型。",
                 options: ["基因重组", "基因突变", "染色体数目变异", "细胞的全能性"],
                 answerIndex: 1),
    ]

    // MARK: 付费内容 · 选必1 高频考点加密（第 2 题）
    private static let homeostasisDense: [Question] = [
        Question(id: "q_hm5_c2", kpId: "h_humor_05", type: .choice,
                 stem: "血液中甲状腺激素含量过高时，会反过来抑制下丘脑和垂体的活动，这种调节方式属于？",
                 explanation: "甲状腺激素增多抑制下丘脑、垂体的分泌，是典型的（负）反馈调节。",
                 options: ["正反馈调节", "负反馈调节", "前馈调节", "非条件反射"],
                 answerIndex: 1),
        Question(id: "q_im3_c2", kpId: "h_immune_03", type: .choice,
                 stem: "系统性红斑狼疮、类风湿性关节炎属于免疫失调中的？",
                 explanation: "自身免疫病是免疫系统过强、把自身物质当作抗原攻击而引起的，如红斑狼疮、类风湿。",
                 options: ["过敏反应", "自身免疫病", "免疫缺陷病", "传染病"],
                 answerIndex: 1),
        Question(id: "q_im6_c2", kpId: "h_immune_06", type: .choice,
                 stem: "下列不属于艾滋病（HIV）传播途径的是？",
                 explanation: "HIV 经性接触、血液和母婴传播；一般的日常接触（握手、共餐）不会传播。",
                 options: ["性接触传播", "血液传播", "母婴传播", "一般日常接触（握手、共餐）"],
                 answerIndex: 3),
        Question(id: "q_env3_c2", kpId: "h_env_03", type: .choice,
                 stem: "过敏反应时毛细血管通透性增大、血浆蛋白渗出到组织液，最可能引起？",
                 explanation: "血浆蛋白渗出使组织液渗透压升高、回流减少，导致组织水肿。",
                 options: ["组织水肿", "血糖升高", "尿量大增", "体温升高"],
                 answerIndex: 0),
        Question(id: "q_pl4_c2", kpId: "h_plant_04", type: .choice,
                 stem: "下列现象能体现生长素作用两重性（低浓度促进、高浓度抑制）的是？",
                 explanation: "顶端优势中，顶芽产生的生长素向下运输使侧芽附近浓度过高而被抑制，体现两重性。",
                 options: ["顶端优势", "植物的有氧呼吸", "种子萌发需要水", "光合作用产生氧气"],
                 answerIndex: 0),
        Question(id: "q_nr3_c2", kpId: "h_nerve_03", type: .choice,
                 stem: "与非条件反射相比，条件反射的特点是？",
                 explanation: "条件反射是后天经过学习训练建立的，需要大脑皮层参与，可消退。",
                 options: ["是后天形成的，需要大脑皮层参与", "生来就有", "不需要神经系统", "与刺激无关"],
                 answerIndex: 0),
    ]

    // MARK: 付费内容 · 选必2 高频考点加密（第 2 题）
    private static let ecologyDense: [Question] = [
        Question(id: "q_cm1_c2", kpId: "e_comm_01", type: .choice,
                 stem: "下列属于初生演替的是？",
                 explanation: "初生演替发生在从未有过生物或原有植被被彻底消灭之处，如裸岩、沙丘、火山岩上的演替。",
                 options: ["弃耕农田上的演替", "火灾后森林的恢复", "裸岩上开始的演替", "过度放牧后草原的恢复"],
                 answerIndex: 2),
        Question(id: "q_cm2_c2", kpId: "e_comm_02", type: .choice,
                 stem: "在“先增加者先减少、后增加者后减少”的捕食关系数量曲线中，先减少的一方通常是？",
                 explanation: "被捕食者数量先于捕食者变化（先增先减），可据此判断捕食与被捕食关系。",
                 options: ["捕食者", "被捕食者", "竞争者", "分解者"],
                 answerIndex: 1),
        Question(id: "q_pop3_c2", kpId: "e_pop_03", type: .choice,
                 stem: "用样方法调查植物种群密度时，最关键的要求是？",
                 explanation: "样方法必须随机取样，避免主观选择，再求多个样方的平均值。",
                 options: ["随机取样", "选择植物最密的地方", "只取一个样方", "选择植物最稀的地方"],
                 answerIndex: 0),
        Question(id: "q_ec4_c2", kpId: "e_eco_04", type: .choice,
                 stem: "信息传递在生态系统中的重要作用之一是？",
                 explanation: "信息传递能调节种间关系，从而维持生态系统的稳定。",
                 options: ["调节种间关系，维持生态系统的稳定", "使能量循环利用", "把能量传递效率提高到 100%", "增大环境容纳量 K"],
                 answerIndex: 0),
        Question(id: "q_pro1_c2", kpId: "e_protect_01", type: .choice,
                 stem: "生物多样性包括的三个层次是？",
                 explanation: "生物多样性包括基因（遗传）多样性、物种多样性和生态系统多样性。",
                 options: ["基因多样性、物种多样性、生态系统多样性", "个体、种群、群落", "细胞、组织、器官", "生产者、消费者、分解者"],
                 answerIndex: 0),
    ]

    // MARK: 付费内容 · 选必3 高频考点加密（第 2 题）
    private static let biotechDense: [Question] = [
        Question(id: "q_pcr_c2", kpId: "b_pcr", type: .choice,
                 stem: "PCR 扩增 DNA 时，除模板、四种脱氧核苷酸和耐高温聚合酶外，还必须加入？",
                 explanation: "PCR 需要一对引物（与模板特定序列互补），DNA 聚合酶只能从引物 3′ 端延伸。",
                 options: ["引物", "限制酶", "运载体", "RNA 聚合酶"],
                 answerIndex: 0),
        Question(id: "q_mab_c2", kpId: "b_mab", type: .choice,
                 stem: "制备单克隆抗体所用的杂交瘤细胞，具有的特点是？",
                 explanation: "杂交瘤细胞由 B 淋巴细胞与骨髓瘤细胞融合而成，既能无限增殖又能产生特异性抗体。",
                 options: ["既能无限增殖，又能产生特异性抗体", "只能增殖、不能产抗体", "只能产抗体、不能增殖", "能进行光合作用"],
                 answerIndex: 0),
        Question(id: "q_trad_c2", kpId: "b_traditional", type: .choice,
                 stem: "制作腐乳和泡菜时，分别主要利用的微生物是？",
                 explanation: "腐乳主要利用毛霉（真菌），泡菜主要利用乳酸菌（无氧发酵产乳酸）。",
                 options: ["毛霉、乳酸菌", "酵母菌、醋酸菌", "乳酸菌、毛霉", "醋酸菌、酵母菌"],
                 answerIndex: 0),
    ]

    // MARK: 付费内容 · 必修2 全面加密（第 2 题，换角度，覆盖率拉满到每点 ≥2）
    private static let geneticsDense2: [Question] = [
        Question(id: "q_ex2_c2", kpId: "g_expr_02", type: .choice,
                 stem: "同一种密码子在不同生物中都编码相同的氨基酸，这说明密码子具有？",
                 explanation: "不同生物共用一套密码子，这是密码子的通用性，也是基因工程能跨物种表达的基础。",
                 options: ["简并性", "通用性", "专一性", "多样性"],
                 answerIndex: 1),
        Question(id: "q_fert_c2", kpId: "g_fert", type: .choice,
                 stem: "受精卵中的染色体（核遗传物质）来源是？",
                 explanation: "受精卵的染色体一半来自父方（精子）、一半来自母方（卵细胞）。",
                 options: ["全部来自母方", "全部来自父方", "一半来自父方、一半来自母方", "随机来自双方"],
                 answerIndex: 2),
        Question(id: "q_method_c2", kpId: "g_method", type: .choice,
                 stem: "孟德尔用测交实验来检验他对 F₁ 遗传组成的推断，这一步在假说—演绎法中属于？",
                 explanation: "用假说去预测测交结果并实验验证，属于“演绎推理与实验验证”环节。",
                 options: ["提出问题", "提出假说", "演绎推理与实验验证", "总结规律"],
                 answerIndex: 2),
        Question(id: "q_dom_c2", kpId: "g_dominance", type: .choice,
                 stem: "要鉴别一只显性性状的动物是纯合子还是杂合子，最简便可靠的方法是？",
                 explanation: "动物不能自交，用测交（与隐性纯合子交配）可据后代是否出现隐性性状判断。",
                 options: ["自交", "测交", "正反交", "直接观察表现型"],
                 answerIndex: 1),
        Question(id: "q_dis_c2", kpId: "g_disease", type: .choice,
                 stem: "下列属于单基因遗传病的是？",
                 explanation: "白化病由一对等位基因控制，属单基因遗传病；21 三体、猫叫综合征属染色体异常遗传病。",
                 options: ["21 三体综合征", "猫叫综合征", "白化病", "流行性感冒"],
                 answerIndex: 2),
        Question(id: "q_mon_c2", kpId: "g_monitor", type: .choice,
                 stem: "禁止近亲结婚的遗传学原因是，近亲结婚会使后代？",
                 explanation: "近亲带有相同隐性致病基因的概率高，结婚会显著升高隐性遗传病的发病风险。",
                 options: ["显性遗传病减少", "完全不会患病", "染色体数目改变", "隐性遗传病发病风险升高"],
                 answerIndex: 3),
        Question(id: "q_sic_c2", kpId: "g_sickle", type: .choice,
                 stem: "镰刀型细胞贫血症患者红细胞异常，其直接原因是？",
                 explanation: "碱基对替换 → 血红蛋白中一个氨基酸（谷氨酸→缬氨酸）改变 → 红细胞镰刀化。",
                 options: ["红细胞数目过多", "血红蛋白中一个氨基酸发生改变", "染色体数目增多", "缺乏血红蛋白"],
                 answerIndex: 1),
        Question(id: "q_cstr_c2", kpId: "g_chrom_struct", type: .choice,
                 stem: "下列不属于染色体结构变异的是？",
                 explanation: "染色体结构变异包括缺失、重复、倒位、易位；基因突变是基因内部碱基的改变，不属于染色体变异。",
                 options: ["缺失", "重复", "倒位", "基因突变"],
                 answerIndex: 3),
        Question(id: "q_cnum_c2", kpId: "g_chrom_num", type: .choice,
                 stem: "由配子（未受精的卵细胞或花粉）直接发育成的个体称为？",
                 explanation: "由配子直接发育而来的个体是单倍体，其体细胞含本物种配子的染色体数目。",
                 options: ["二倍体", "单倍体", "多倍体", "纯合子"],
                 answerIndex: 1),
        Question(id: "q_hap_c2", kpId: "g_haploid", type: .choice,
                 stem: "单倍体育种中，常用花药离体培养获得单倍体幼苗后，再用秋水仙素处理使其？",
                 explanation: "单倍体高度不育，需用秋水仙素使染色体数目加倍，得到能正常繁殖的纯合二倍体。",
                 options: ["发生基因突变", "进行减数分裂", "染色体数目加倍（恢复正常）", "发生基因重组"],
                 answerIndex: 2),
        Question(id: "q_coevo_c2", kpId: "g_coevo", type: .choice,
                 stem: "地球上丰富多彩的生物多样性，其形成的主要原因是？",
                 explanation: "生物多样性是生物与生物、生物与无机环境长期协同进化的结果。",
                 options: ["一次性的基因突变", "人工选择", "地理隔离的消失", "长期的协同进化"],
                 answerIndex: 3),
    ]

    // MARK: 付费内容 · 选必1 全面加密（第 2 题）一
    private static let homeostasisDense2: [Question] = [
        Question(id: "q_hm2_c2", kpId: "h_humor_02", type: .choice,
                 stem: "寒冷环境中，人体增加产热的主要方式是？",
                 explanation: "寒冷时骨骼肌不自主战栗、甲状腺激素和肾上腺素分泌增多，使代谢加强、产热增加。",
                 options: ["大量出汗", "骨骼肌不自主战栗，甲状腺激素和肾上腺素分泌增多", "皮肤血管舒张", "减慢呼吸"],
                 answerIndex: 1),
        Question(id: "q_pl1_c2", kpId: "h_plant_01", type: .choice,
                 stem: "植物表现出向光生长，其原因是单侧光使生长素？",
                 explanation: "单侧光使生长素在背光侧分布多，背光侧生长快，向光侧生长慢，植物便向光弯曲。",
                 options: ["在向光侧分布多", "被全部分解", "在背光侧分布多，背光侧生长快", "停止运输"],
                 answerIndex: 2),
        Question(id: "q_hm3_c2", kpId: "h_humor_03", type: .choice,
                 stem: "人大量出汗后细胞外液渗透压升高，机体的调节反应是？",
                 explanation: "渗透压升高→下丘脑渗透压感受器兴奋→垂体释放抗利尿激素增多→重吸收水增多→尿量减少。",
                 options: ["抗利尿激素分泌增多，尿量减少", "抗利尿激素分泌减少，尿量增多", "胰岛素分泌增多", "尿量保持不变"],
                 answerIndex: 0),
        Question(id: "q_im2_c2", kpId: "h_immune_02", type: .choice,
                 stem: "人体免疫系统的组成是？",
                 explanation: "免疫系统由免疫器官、免疫细胞和免疫活性物质（如抗体、淋巴因子）组成。",
                 options: ["只有白细胞", "只有抗体", "皮肤和黏膜", "免疫器官、免疫细胞和免疫活性物质"],
                 answerIndex: 3),
        Question(id: "q_pl2_c2", kpId: "h_plant_02", type: .choice,
                 stem: "能促进细胞伸长、解除种子休眠并促进萌发的植物激素是？",
                 explanation: "赤霉素能促进细胞伸长、引起植株增高，并能解除休眠、促进种子萌发。",
                 options: ["脱落酸", "赤霉素", "乙烯", "细胞分裂素"],
                 answerIndex: 1),
        Question(id: "q_env2_c2", kpId: "h_env_02", type: .choice,
                 stem: "血浆渗透压的大小主要取决于？",
                 explanation: "血浆渗透压主要由其中无机盐和蛋白质的含量决定。",
                 options: ["葡萄糖含量", "氧气含量", "无机盐和蛋白质的含量", "温度高低"],
                 answerIndex: 2),
        Question(id: "q_nr4_c2", kpId: "h_nerve_04", type: .choice,
                 stem: "兴奋在突触处只能由突触前膜传向突触后膜（单向）的原因是？",
                 explanation: "神经递质只能由突触前膜释放、经间隙作用于突触后膜上的受体，故只能单向传递。",
                 options: ["神经递质只能由突触前膜释放、作用于突触后膜", "突触后膜不能接受信号", "突触间隙太宽", "递质能在间隙内双向移动"],
                 answerIndex: 0),
    ]

    // MARK: 付费内容 · 选必1 全面加密（第 2 题）二
    private static let homeostasisDense3: [Question] = [
        Question(id: "q_nr5_c2", kpId: "h_nerve_05", type: .choice,
                 stem: "下列属于人脑特有的高级功能的是？",
                 explanation: "语言是人脑特有的高级功能；膝跳反射、心跳、呼吸等较低级中枢也能完成。",
                 options: ["膝跳反射", "心跳", "呼吸", "语言（言语）功能"],
                 answerIndex: 3),
        Question(id: "q_hm4_c2", kpId: "h_humor_04", type: .choice,
                 stem: "激素被靶细胞接受并起作用后，一般会？",
                 explanation: "激素一经发挥作用后就被灭活（降解），因此需要源源不断地产生以维持调节。",
                 options: ["永久保留在体内", "被灭活（降解）", "返回内分泌腺重复使用", "转变为消化酶"],
                 answerIndex: 1),
        Question(id: "q_im4_c2", kpId: "h_immune_04", type: .choice,
                 stem: "人体的第一道防线（皮肤、黏膜）和第二道防线（杀菌物质、吞噬细胞）属于？",
                 explanation: "前两道防线人人生来就有、对多种病原体都起作用，属非特异性免疫。",
                 options: ["非特异性免疫", "特异性免疫", "体液免疫", "细胞免疫"],
                 answerIndex: 0),
        Question(id: "q_im5_c2", kpId: "h_immune_05", type: .choice,
                 stem: "器官移植时发生的免疫排斥反应，主要与哪种免疫有关？",
                 explanation: "移植器官作为“异己”被细胞毒性 T 细胞攻击，排斥反应主要是细胞免疫。",
                 options: ["第一道防线", "非特异性免疫", "细胞免疫", "体液免疫产生抗体"],
                 answerIndex: 2),
        Question(id: "q_pl3_c2", kpId: "h_plant_03", type: .choice,
                 stem: "达尔文父子的向光性实验表明，能感受单侧光刺激的部位是胚芽鞘的？",
                 explanation: "达尔文实验证明胚芽鞘尖端能感受单侧光，弯曲生长发生在尖端下面一段。",
                 options: ["尖端", "尖端下面一段", "基部", "整个胚芽鞘"],
                 answerIndex: 0),
        Question(id: "q_pl5_c2", kpId: "h_plant_05", type: .choice,
                 stem: "一定高浓度的生长素类似物可用作除草剂，其原理是？",
                 explanation: "双子叶杂草比单子叶农作物对生长素更敏感，高浓度可抑制甚至杀死双子叶杂草而不伤庄稼。",
                 options: ["能直接毒死所有杂草", "抑制杂草光合作用", "杀死田里所有植物", "双子叶杂草比单子叶作物对生长素更敏感"],
                 answerIndex: 3),
    ]

    // MARK: 付费内容 · 选必2 全面加密（第 2 题）
    private static let ecologyDense2: [Question] = [
        Question(id: "q_ec1_c2", kpId: "e_eco_01", type: .choice,
                 stem: "生态系统的营养结构是指？",
                 explanation: "食物链和食物网是生态系统的营养结构，是物质循环和能量流动的渠道。",
                 options: ["食物链和食物网", "生产者", "非生物的物质和能量", "所有生物的总和"],
                 answerIndex: 0),
        Question(id: "q_pop2_c2", kpId: "e_pop_02", type: .choice,
                 stem: "种群最基本的数量特征是？",
                 explanation: "种群密度是种群最基本的数量特征；出生率死亡率、迁入迁出率直接决定种群密度。",
                 options: ["年龄组成", "种群密度", "性别比例", "物种丰富度"],
                 answerIndex: 1),
        Question(id: "q_pop4_c2", kpId: "e_pop_04", type: .choice,
                 stem: "许多昆虫常成群聚集在一起，这种空间分布类型属于？",
                 explanation: "个体成群、成簇分布属于集群分布，是最常见的空间分布型。",
                 options: ["均匀分布", "随机分布", "集群分布", "垂直分布"],
                 answerIndex: 2),
        Question(id: "q_cm3_c2", kpId: "e_comm_03", type: .choice,
                 stem: "一个物种在群落中所处的空间位置、占用的资源以及与其他物种的关系，称为该物种的？",
                 explanation: "生态位指物种在群落中的地位或作用，包括栖息空间、食物及与其他物种的关系。",
                 options: ["种群密度", "物种丰富度", "营养级", "生态位"],
                 answerIndex: 3),
        Question(id: "q_ec6_c2", kpId: "e_eco_06", type: .choice,
                 stem: "生态系统能量流动的特点是？",
                 explanation: "能量流动是单向流动、逐级递减的，传递效率约 10%~20%，不能循环利用。",
                 options: ["单向流动、逐级递减", "循环流动", "逐级递增", "双向流动、保持不变"],
                 answerIndex: 0),
        Question(id: "q_ec8_c2", kpId: "e_eco_08", type: .choice,
                 stem: "与喷洒农药相比，利用昆虫信息素防治害虫的主要优点是？",
                 explanation: "信息素防治污染小、不杀伤天敌、害虫不易产生抗性，属于生物防治。",
                 options: ["见效更快", "减少环境污染、不杀伤天敌", "成本为零", "能彻底灭绝害虫"],
                 answerIndex: 1),
        Question(id: "q_ec10_c2", kpId: "e_eco_10", type: .choice,
                 stem: "在物质循环和能量流动的关系中，能量所起的作用是？",
                 explanation: "物质是能量流动的载体，能量是物质在生态系统中循环往返的动力。",
                 options: ["作为物质循环的载体", "使物质逐级递减", "作为物质循环的动力", "与物质循环无关"],
                 answerIndex: 2),
        Question(id: "q_pro2_c2", kpId: "e_protect_02", type: .choice,
                 stem: "大量使用氟氯烃（氟利昂）等物质，会破坏？",
                 explanation: "氟氯烃会破坏大气臭氧层，形成臭氧层空洞，使到达地面的紫外线增强。",
                 options: ["水圈", "岩石圈", "食物链", "臭氧层（形成臭氧层空洞）"],
                 answerIndex: 3),
        Question(id: "q_pro3_c2", kpId: "e_protect_03", type: .choice,
                 stem: "为协调人与环境的关系，人类社会应走的发展道路是？",
                 explanation: "可持续发展追求经济、社会和生态的持久而协调的发展。",
                 options: ["可持续发展道路", "先污染后治理", "无限度开发资源", "只追求经济增长"],
                 answerIndex: 0),
    ]

    // MARK: 付费内容 · 选必3 全面加密（第 2 题）
    private static let biotechDense2: [Question] = [
        Question(id: "q_ferm_c2", kpId: "b_ferment_01", type: .choice,
                 stem: "利用酵母菌制作果酒时，发酵所需的条件是？",
                 explanation: "酵母菌制果酒是无氧发酵，需密封造成无氧环境；前期可适当通气利于其繁殖。",
                 options: ["无氧（密封）", "持续通入大量空气", "高温煮沸", "强光照射"],
                 answerIndex: 0),
        Question(id: "q_pcl_c2", kpId: "b_cell_01", type: .choice,
                 stem: "植物组织培养中，离体的植物组织经脱分化形成的是？",
                 explanation: "脱分化使高度分化的细胞恢复分裂能力，形成未分化的愈伤组织，再分化成植株。",
                 options: ["胚状体", "愈伤组织", "原生质体", "成熟花粉"],
                 answerIndex: 1),
        Question(id: "q_cl2_c2", kpId: "b_cell_02", type: .choice,
                 stem: "多数动物细胞需附着在培养瓶壁上才能正常生长增殖，这种特性称为？",
                 explanation: "动物细胞培养具有贴壁生长（贴壁依赖性）的特点；细胞铺满瓶壁后会出现接触抑制。",
                 options: ["接触抑制", "细胞凋亡", "贴壁生长（贴壁依赖性）", "全能性"],
                 answerIndex: 2),
        Question(id: "q_emb_c2", kpId: "b_embryo_01", type: .choice,
                 stem: "哺乳动物体外受精前，需要对精子进行的处理是？",
                 explanation: "精子需经获能处理才具备受精能力；卵母细胞则需培养至减数第二次分裂中期。",
                 options: ["脱水处理", "低温冷冻", "紫外照射", "获能处理"],
                 answerIndex: 3),
        Question(id: "q_med_c2", kpId: "b_medium", type: .choice,
                 stem: "“灭菌”与“消毒”的主要区别是？",
                 explanation: "灭菌杀灭包括芽孢在内的全部微生物；消毒只杀灭物体表面或内部的部分微生物。",
                 options: ["灭菌杀灭全部微生物（含芽孢），消毒只杀灭部分", "二者完全相同", "消毒比灭菌更彻底", "灭菌只针对细菌"],
                 answerIndex: 0),
        Question(id: "q_iso_c2", kpId: "b_isolate", type: .choice,
                 stem: "通过连续划线将聚集的菌种逐步稀释、分散到培养基表面，从而获得单个菌落的方法是？",
                 explanation: "平板划线法通过接种环在平板上连续划线稀释菌液，可分离得到单个菌落。",
                 options: ["紫外诱变", "平板划线法", "花药离体培养", "显微注射"],
                 answerIndex: 1),
        Question(id: "q_pcl2_c2", kpId: "b_plant_clone", type: .choice,
                 stem: "植物体细胞杂交技术的最大优点是能克服？",
                 explanation: "体细胞杂交可让远缘物种的体细胞融合，克服远缘杂交不亲和的障碍。",
                 options: ["基因突变", "染色体变异", "远缘杂交不亲和的障碍", "细胞分化"],
                 answerIndex: 2),
        Question(id: "q_ac_c2", kpId: "b_animal_culture", type: .choice,
                 stem: "动物细胞培养液中，通常需要加入的天然成分是？",
                 explanation: "培养液成分包括糖、氨基酸、无机盐、维生素等，通常还需加入血清等天然成分。",
                 options: ["琼脂", "秋水仙素", "限制酶", "血清等天然成分"],
                 answerIndex: 3),
        Question(id: "q_gapp_c2", kpId: "b_gene_app", type: .choice,
                 stem: "培育抗虫棉时，导入棉花细胞的目的基因通常是？",
                 explanation: "抗虫棉常导入苏云金芽孢杆菌的抗虫基因（Bt 毒蛋白基因），使棉花自身能抗虫。",
                 options: ["抗虫基因（如苏云金芽孢杆菌毒蛋白基因）", "人胰岛素基因", "生长激素基因", "血红蛋白基因"],
                 answerIndex: 0),
        Question(id: "q_safe_c2", kpId: "b_safety", type: .choice,
                 stem: "对转基因生物安全性的争论，主要涉及？",
                 explanation: "转基因生物安全性主要涉及食物安全、生物安全和环境安全三方面。",
                 options: ["运输安全", "食物安全、生物安全和环境安全", "审美问题", "经济成本"],
                 answerIndex: 1),
    ]
}
