import Foundation

// MARK: - 武器库教学数据（家族标配）
// 每把武器：何时用(识局) → 怎么用(步骤) → 例题(破题之眼) / 去哪练。

enum WeaponData {
    static let all: [WeaponGuide] = [
        WeaponGuide(weapon: .isotope, tagline: "追踪原子的来龙去脉",
            whenToUse: ["题目问「某原子/元素来自哪里、去了哪里」", "涉及光合、呼吸、分泌蛋白合成运输等过程的物质来源"],
            steps: ["给目标原子换成可检测的同位素（如 ¹⁸O、³²P、³⁵S、¹⁴C）",
                    "顺着过程追踪它进入了哪个产物",
                    "对比不同标记组的结果得出来源/去向"],
            exampleChallengeId: "ch_isotope"),
        WeaponGuide(weapon: .extremeValue, tagline: "推到两个极端，答案夹在中间",
            whenToUse: ["求能量流动的最多/最少", "混合物比例未知、求范围"],
            steps: ["确定两个极端条件（如最高/最低传递效率）", "分别算出两个极值", "真实结果落在两值之间；按题意取对应极端"],
            exampleChallengeId: "ch_energy"),
        WeaponGuide(weapon: .hypothesis, tagline: "先假设，再看是否矛盾",
            whenToUse: ["判断显隐性、遗传方式（常/X）", "已知部分结果、需排除某种可能"],
            steps: ["提出一个假设（如假设伴 X 隐性）", "在该假设下推出必然结果", "与题目已知比对：矛盾则排除，不矛盾则成立"],
            exampleChallengeId: "ch_hypothesis"),
        WeaponGuide(weapon: .hardyWeinberg, tagline: "遗传平衡下用频率公式",
            whenToUse: ["已知发病率求基因频率/携带者比例", "竞赛或拔高的群体遗传计算"],
            steps: ["隐性纯合 aa 频率 = q²", "开平方得 q，再求 p = 1 − q", "携带者 Aa = 2pq；显性 = p² + 2pq"],
            exampleChallengeId: "ch_hw"),
        WeaponGuide(weapon: .dataInsight, tagline: "从数据/比值里读出过程",
            whenToUse: ["给出 RQ、比值、坐标数据要判断过程或类型", "异常数据需要解释"],
            steps: ["明确各数据的生物学含义", "与「标准值」比较（如 RQ=1）", "由偏离方向反推发生了什么"],
            exampleChallengeId: "ch_rq"),
        WeaponGuide(weapon: .probability, tagline: "复杂概率拆成独立事件相乘",
            whenToUse: ["多对基因、多步骤求某结果的概率", "患病/正常/携带者概率"],
            steps: ["把事件拆成相互独立的几个", "分别求每个的概率", "同时发生相乘、互斥相加"],
            exampleChallengeId: "ch_prob", practiceHint: "去「遗传秒算」练手"),
        WeaponGuide(weapon: .gamete, tagline: "先定配子，再组合后代",
            whenToUse: ["求后代基因型/表现型种类与比例", "含连锁或特殊配子比例"],
            steps: ["写出每个亲本产生的配子种类及比例", "配子两两组合（棋盘或相乘）", "合并相同基因型，得后代比例"],
            exampleChallengeId: "ch_gamete", practiceHint: "去「遗传秒算」练手"),
        WeaponGuide(weapon: .pedigree, tagline: "系谱三步：显隐 → 常/X → 概率",
            whenToUse: ["给出家族系谱图判断遗传方式或求概率"],
            steps: ["看「无中生有/有中生无」定显隐", "用女患者之父、男患者之母排除或确定 X", "据基因型按概率计算"],
            exampleChallengeId: "ch_pedigree", practiceHint: "去「遗传神探」破案"),
        WeaponGuide(weapon: .graphReading, tagline: "看轴 → 看点 → 看拐点",
            whenToUse: ["任何坐标曲线/柱状/数据图题"],
            steps: ["先看横纵坐标各代表什么、单位", "找起点、终点、交点、最高/最低点的含义", "看拐点与趋势对应什么变化"],
            exampleChallengeId: "ch_graph", practiceHint: "去「图表曲线分析」专练"),
        WeaponGuide(weapon: .control, tagline: "单一变量 + 对照 + 等量",
            whenToUse: ["实验设计与分析、评价实验是否严谨"],
            steps: ["找准自变量、因变量、无关变量", "设置对照（空白/相互对照）", "无关变量等量且适宜，只让自变量变化"],
            exampleChallengeId: "ch_control", practiceHint: "去「探究实验台」闯关"),
        WeaponGuide(weapon: .scoring, tagline: "答到点、用术语，大题靠踩分",
            whenToUse: ["简答题、原因分析、实验结论的规范表述"],
            steps: ["先想清逻辑链：原因 → 机制 → 结果", "逐条对应采分点，用规范术语", "因果完整、不漏关键词"],
            exampleChallengeId: "ch_scoring", practiceHint: "去「简答采分训练」对照采分点"),
        WeaponGuide(weapon: .baseCount, tagline: "互补配对 + 6∶3∶1，把数量算到底",
            whenToUse: ["已知一条链碱基比例，求另一条链或整个 DNA", "由基因/DNA 碱基数推 mRNA 碱基数、氨基酸数", "DNA 复制 n 次消耗的游离碱基数"],
            steps: ["互补配对：A=T、G=C；双链中 (A+G)=(T+C)＝总数的一半",
                    "一条链的 (A+T)/(G+C) 与整个 DNA 相同；某链与互补链的 (A+G)/(T+C) 互为倒数",
                    "中心法则数量关系：基因碱基数∶mRNA 碱基数∶氨基酸数 ≈ 6∶3∶1",
                    "复制 n 次消耗某游离碱基 =（2ⁿ−1）× 该碱基在 DNA 中的数目"],
            exampleChallengeId: "ch_base_1"),
        WeaponGuide(weapon: .crossDesign, tagline: "自交还是测交，鉴定靠设计",
            whenToUse: ["鉴定一对相对性状的显隐性", "鉴定某显性个体是纯合还是杂合", "依材料能否自交选择不同方案"],
            steps: ["判显隐：纯合亲本正交看 F₁（显性先现），或让其自交看后代是否性状分离",
                    "鉴定纯合/杂合：植物优先自交（后代不分离=纯合、分离=杂合）",
                    "动物或不宜自交时用测交（与隐性纯合交，后代不分离=纯合、分离=杂合）",
                    "写清每种预期结果对应的结论，覆盖所有可能"],
            exampleChallengeId: "ch_cross_2"),
        WeaponGuide(weapon: .linkage, tagline: "亲本型多、重组型少，就是连锁",
            whenToUse: ["双杂合测交后代不是 1∶1∶1∶1（亲本型远多于重组型）", "求重组率/遗传图距", "判断两对基因是否连锁"],
            steps: ["双杂合测交：后代 1∶1∶1∶1 → 自由组合；亲本型≫重组型 → 连锁",
                    "重组率 = 重组型个体数 ÷ 总个体数 × 100%",
                    "重组率≈图距（厘摩 cM），可用于基因排序定位",
                    "完全连锁时只有亲本型、无重组型"],
            exampleChallengeId: "ch_link_1"),
        WeaponGuide(weapon: .energyBudget, tagline: "摄入＝同化＋粪便，同化＝呼吸＋生长",
            whenToUse: ["某营养级能量的去向/来源分配", "已知同化量求流入下一营养级或被分解者的量", "判断粪便能量属于哪个营养级"],
            steps: ["摄入量 = 同化量 + 粪便量（粪便属上一营养级同化的能量）",
                    "同化量 = 呼吸消耗 + 用于生长发育和繁殖",
                    "用于生长发育繁殖 = 流入下一营养级 + 被分解者利用 + 未利用",
                    "按题目能量流动图逐项代入求差"],
            exampleChallengeId: "ch_ebudget_1"),
        WeaponGuide(weapon: .gasExchange, tagline: "净光合＋呼吸＝总光合",
            whenToUse: ["黑白瓶/密闭装置测气体变化", "由表观（净）光合求真正（总）光合", "昼夜有机物积累计算"],
            steps: ["黑暗中气体变化 = 呼吸作用强度",
                    "光下气体净变化 = 净（表观）光合",
                    "总（真正）光合 = 净光合 + 呼吸",
                    "需用黑瓶/遮光单独测呼吸，白瓶测净光合"],
            exampleChallengeId: "ch_gas_1"),
        WeaponGuide(weapon: .divisionImage, tagline: "看染色体行为，定分裂时期",
            whenToUse: ["给细胞分裂图判断有丝/减数及时期", "染色体/DNA/染色单体数目变化曲线", "判断细胞名称"],
            steps: ["看有无同源染色体配对/分开：有联会四分体或同源分开 → 减数分裂",
                    "数着丝点 = 染色体数；看是否有姐妹染色单体（复制后未分开）",
                    "后期着丝点分裂 → 姐妹染色单体分开成染色体，数目暂时加倍",
                    "结合是否均等分裂、有无同源判断时期与细胞名称"],
            exampleChallengeId: "ch_divimg_1"),
        WeaponGuide(weapon: .osmosis, tagline: "比浓度，定吸水还是失水",
            whenToUse: ["质壁分离与复原的判断", "判断细胞吸水/失水", "比较细胞液与外界溶液浓度"],
            steps: ["成熟植物细胞是渗透系统（原生质层相当于半透膜）",
                    "外界溶液浓度 > 细胞液浓度 → 失水 → 质壁分离",
                    "外界溶液浓度 < 细胞液浓度 → 吸水 → 质壁分离复原",
                    "由能否自动复原反推外界溶液是否被吸收/是否过浓致死"],
            exampleChallengeId: "ch_osmosis_1"),
        WeaponGuide(weapon: .variationType, tagline: "可遗传三选一：突变·重组·染色体变异",
            whenToUse: ["判断某变异属于哪种类型", "区分可遗传与不可遗传变异", "由变异结果反推变异来源"],
            steps: ["先判可遗传（遗传物质改变）还是不可遗传（仅环境引起）",
                    "基因突变：DNA 碱基增添/缺失/替换，产生新基因（新的等位基因）",
                    "基因重组：减数分裂中非等位基因重新组合（自由组合或交叉互换），不产生新基因",
                    "染色体变异：结构（缺失/重复/倒位/易位）或数目改变，光学显微镜可见"],
            exampleChallengeId: "ch_vartype_1"),
        WeaponGuide(weapon: .geneticDiagram, tagline: "亲本→配子→子代，分点写规范",
            whenToUse: ["大题要求写出遗传图解", "推导杂交结果并规范表达", "书写配子与子代比例"],
            steps: ["写明亲本表现型与基因型，标注 ♀♂ 与杂交符号 ×",
                    "写出各亲本产生的配子（用圈标出）",
                    "写出子代基因型、表现型及比例",
                    "注明性状显隐/性别，比例化到最简"],
            exampleChallengeId: "ch_gdiagram_1"),
        WeaponGuide(weapon: .specialRatio, tagline: "9:3:3:1 变了形，本质仍自由组合",
            whenToUse: ["F₂ 出现 9:7、9:6:1、15:1、12:3:1、13:3 等比例", "出现 2:1 等致死比例", "由异常分离比反推基因互作或致死"],
            steps: ["先把比例总份数凑成 16（或其约数）→ 多半是 9:3:3:1 的变式（基因互作）",
                    "把 9/3/3/1 按表现型合并：如 9:7=9:(3+3+1)、15:1=(9+3+3):1",
                    "出现 2:1 提示某纯合致死（如 Aa×Aa 中 AA 致死）",
                    "据合并方式推断两对基因如何共同决定性状"],
            exampleChallengeId: "ch_sratio_1"),
        WeaponGuide(weapon: .populationModel, tagline: "J 型看 λ，S 型看 K/2",
            whenToUse: ["种群数量随时间变化（J/S 型曲线）", "已知初始数量与增长倍数求数量", "K 值、K/2 的应用（防治/捕捞）"],
            steps: ["J 型（理想、资源无限）：Nₜ = N₀·λᵗ，λ 为每代倍数（>1 增、=1 不变、<1 减）",
                    "S 型（资源有限）：受环境阻力，达 K（环境容纳量）停止增长",
                    "S 型增长速率在 K/2 时最大、K 时为 0",
                    "应用：害虫防治在 K/2 前压低；持续捕捞后保持 K/2"],
            exampleChallengeId: "ch_popmodel_1"),
        WeaponGuide(weapon: .assignValue, tagline: "未知设具体值，抽象变具体",
            whenToUse: ["比例/频率没给具体数、直接算易绕晕", "证明某比例关系", "多步骤百分数运算"],
            steps: ["给总数或某量设便于计算的具体值（如 1、100 或 16）",
                    "按题意逐步算出各部分的具体数值",
                    "再换算回比例或百分数",
                    "所设值不影响最终比例（结论具一般性）"],
            exampleChallengeId: "ch_assign_1"),
        WeaponGuide(weapon: .microCount, tagline: "菌落数 × 稀释倍数 ÷ 体积",
            whenToUse: ["稀释涂布平板法统计活菌数", "血细胞计数板显微计数", "由平板菌落数反推原液浓度"],
            steps: ["稀释涂布：取适当稀释度，每皿菌落数 30~300 较准",
                    "每毫升活菌数 = 菌落平均数 × 稀释倍数 ÷ 涂布体积(mL)",
                    "稀释涂布计数偏小（多个细胞连一起只成一个菌落）",
                    "血细胞计数板数总数（含死菌）偏大；需设空白对照检验灭菌"],
            exampleChallengeId: "ch_microcount_1"),
        WeaponGuide(weapon: .reverse, tagline: "由产物/子代倒推原料/亲代",
            whenToUse: ["已知子代表现型/比例，反推亲本基因型", "已知最高营养级所得能量，反推第一营养级最少消耗", "已知产物量反推原料/某阶段"],
            steps: ["明确「已知的是结果、要求的是源头」", "选对反推系数（能量最少消耗用最高效率 20%、最多消耗用最低效率 10%；遗传反推用配子/分离比）", "从结果一步步逆向推回，注意单位与范围"],
            exampleChallengeId: "ch_reverse", practiceHint: "去「遗传秒算」「破题之眼」练逆向推理"),
    ]

    static func guide(for weapon: BioWeapon) -> WeaponGuide? { all.first { $0.weapon == weapon } }
}
